// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/interview/v1/interview.proto

package interviewv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "makejob/api/makejob/shared/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateInterviewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IndustryCode   string                 `protobuf:"bytes,2,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Difficulty     string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Topics         []string               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	QuestionCount  int32                  `protobuf:"varint,5,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	Live2DModelKey string                 `protobuf:"bytes,6,opt,name=live2d_model_key,json=live2dModelKey,proto3" json:"live2d_model_key,omitempty"`
	InterviewMode  string                 `protobuf:"bytes,7,opt,name=interview_mode,json=interviewMode,proto3" json:"interview_mode,omitempty"`
	ResumeText     string                 `protobuf:"bytes,8,opt,name=resume_text,json=resumeText,proto3" json:"resume_text,omitempty"`
	JobDescription string                 `protobuf:"bytes,9,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInterviewRequest) Reset() {
	*x = CreateInterviewRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterviewRequest) ProtoMessage() {}

func (x *CreateInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterviewRequest.ProtoReflect.Descriptor instead.
func (*CreateInterviewRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInterviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateInterviewRequest) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *CreateInterviewRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateInterviewRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CreateInterviewRequest) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *CreateInterviewRequest) GetLive2DModelKey() string {
	if x != nil {
		return x.Live2DModelKey
	}
	return ""
}

func (x *CreateInterviewRequest) GetInterviewMode() string {
	if x != nil {
		return x.InterviewMode
	}
	return ""
}

func (x *CreateInterviewRequest) GetResumeText() string {
	if x != nil {
		return x.ResumeText
	}
	return ""
}

func (x *CreateInterviewRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type InterviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FirstQuestion *InterviewQuestion     `protobuf:"bytes,3,opt,name=first_question,json=firstQuestion,proto3" json:"first_question,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterviewResponse) Reset() {
	*x = InterviewResponse{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewResponse) ProtoMessage() {}

func (x *InterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewResponse.ProtoReflect.Descriptor instead.
func (*InterviewResponse) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{2}
}

func (x *InterviewResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterviewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InterviewResponse) GetFirstQuestion() *InterviewQuestion {
	if x != nil {
		return x.FirstQuestion
	}
	return nil
}

func (x *InterviewResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type InterviewDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IndustryCode  string                 `protobuf:"bytes,3,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InterviewMode string                 `protobuf:"bytes,5,opt,name=interview_mode,json=interviewMode,proto3" json:"interview_mode,omitempty"`
	Messages      []*InterviewMessage    `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
	Report        *InterviewReport       `protobuf:"bytes,7,opt,name=report,proto3" json:"report,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterviewDetail) Reset() {
	*x = InterviewDetail{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewDetail) ProtoMessage() {}

func (x *InterviewDetail) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewDetail.ProtoReflect.Descriptor instead.
func (*InterviewDetail) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{3}
}

func (x *InterviewDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterviewDetail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InterviewDetail) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *InterviewDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InterviewDetail) GetInterviewMode() string {
	if x != nil {
		return x.InterviewMode
	}
	return ""
}

func (x *InterviewDetail) GetMessages() []*InterviewMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InterviewDetail) GetReport() *InterviewReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *InterviewDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type InterviewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterviewMessage) Reset() {
	*x = InterviewMessage{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewMessage) ProtoMessage() {}

func (x *InterviewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewMessage.ProtoReflect.Descriptor instead.
func (*InterviewMessage) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{4}
}

func (x *InterviewMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterviewMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InterviewMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InterviewMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *InterviewMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type InterviewQuestion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Question        string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Difficulty      string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Hints           string                 `protobuf:"bytes,5,opt,name=hints,proto3" json:"hints,omitempty"`
	Language        string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	StarterCode     string                 `protobuf:"bytes,7,opt,name=starter_code,json=starterCode,proto3" json:"starter_code,omitempty"`
	EditorMode      string                 `protobuf:"bytes,8,opt,name=editor_mode,json=editorMode,proto3" json:"editor_mode,omitempty"`
	EvaluationMode  string                 `protobuf:"bytes,9,opt,name=evaluation_mode,json=evaluationMode,proto3" json:"evaluation_mode,omitempty"`
	Live2DDirective *Live2DDirective       `protobuf:"bytes,10,opt,name=live2d_directive,json=live2dDirective,proto3" json:"live2d_directive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterviewQuestion) Reset() {
	*x = InterviewQuestion{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewQuestion) ProtoMessage() {}

func (x *InterviewQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewQuestion.ProtoReflect.Descriptor instead.
func (*InterviewQuestion) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{5}
}

func (x *InterviewQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *InterviewQuestion) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InterviewQuestion) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *InterviewQuestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InterviewQuestion) GetHints() string {
	if x != nil {
		return x.Hints
	}
	return ""
}

func (x *InterviewQuestion) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InterviewQuestion) GetStarterCode() string {
	if x != nil {
		return x.StarterCode
	}
	return ""
}

func (x *InterviewQuestion) GetEditorMode() string {
	if x != nil {
		return x.EditorMode
	}
	return ""
}

func (x *InterviewQuestion) GetEvaluationMode() string {
	if x != nil {
		return x.EvaluationMode
	}
	return ""
}

func (x *InterviewQuestion) GetLive2DDirective() *Live2DDirective {
	if x != nil {
		return x.Live2DDirective
	}
	return nil
}

type Live2DDirective struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Emotion            string                     `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Action             string                     `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Reply              string                     `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	ExpressionMix      []*Live2DExpressionLayer   `protobuf:"bytes,4,rep,name=expression_mix,json=expressionMix,proto3" json:"expression_mix,omitempty"`
	ParameterOverrides []*Live2DParameterOverride `protobuf:"bytes,5,rep,name=parameter_overrides,json=parameterOverrides,proto3" json:"parameter_overrides,omitempty"`
	MotionKey          string                     `protobuf:"bytes,6,opt,name=motion_key,json=motionKey,proto3" json:"motion_key,omitempty"`
	MotionGroup        string                     `protobuf:"bytes,7,opt,name=motion_group,json=motionGroup,proto3" json:"motion_group,omitempty"`
	MotionDurationMs   int32                      `protobuf:"varint,8,opt,name=motion_duration_ms,json=motionDurationMs,proto3" json:"motion_duration_ms,omitempty"`
	Intensity          float64                    `protobuf:"fixed64,9,opt,name=intensity,proto3" json:"intensity,omitempty"`
	DurationMs         int32                      `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Live2DDirective) Reset() {
	*x = Live2DDirective{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live2DDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live2DDirective) ProtoMessage() {}

func (x *Live2DDirective) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live2DDirective.ProtoReflect.Descriptor instead.
func (*Live2DDirective) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{6}
}

func (x *Live2DDirective) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *Live2DDirective) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Live2DDirective) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *Live2DDirective) GetExpressionMix() []*Live2DExpressionLayer {
	if x != nil {
		return x.ExpressionMix
	}
	return nil
}

func (x *Live2DDirective) GetParameterOverrides() []*Live2DParameterOverride {
	if x != nil {
		return x.ParameterOverrides
	}
	return nil
}

func (x *Live2DDirective) GetMotionKey() string {
	if x != nil {
		return x.MotionKey
	}
	return ""
}

func (x *Live2DDirective) GetMotionGroup() string {
	if x != nil {
		return x.MotionGroup
	}
	return ""
}

func (x *Live2DDirective) GetMotionDurationMs() int32 {
	if x != nil {
		return x.MotionDurationMs
	}
	return 0
}

func (x *Live2DDirective) GetIntensity() float64 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *Live2DDirective) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Live2DExpressionLayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live2DExpressionLayer) Reset() {
	*x = Live2DExpressionLayer{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live2DExpressionLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live2DExpressionLayer) ProtoMessage() {}

func (x *Live2DExpressionLayer) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live2DExpressionLayer.ProtoReflect.Descriptor instead.
func (*Live2DExpressionLayer) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{7}
}

func (x *Live2DExpressionLayer) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Live2DExpressionLayer) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Live2DParameterOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live2DParameterOverride) Reset() {
	*x = Live2DParameterOverride{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live2DParameterOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live2DParameterOverride) ProtoMessage() {}

func (x *Live2DParameterOverride) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live2DParameterOverride.ProtoReflect.Descriptor instead.
func (*Live2DParameterOverride) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{8}
}

func (x *Live2DParameterOverride) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *Live2DParameterOverride) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SubmitAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionIndex int32                  `protobuf:"varint,3,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitAnswerRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *SubmitAnswerRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitAnswerRequest) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

func (x *SubmitAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitAnswerRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AnswerFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,4,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	Suggestions   string                 `protobuf:"bytes,5,opt,name=suggestions,proto3" json:"suggestions,omitempty"`
	FollowUp      string                 `protobuf:"bytes,6,opt,name=follow_up,json=followUp,proto3" json:"follow_up,omitempty"`
	NextQuestion  *InterviewQuestion     `protobuf:"bytes,7,opt,name=next_question,json=nextQuestion,proto3" json:"next_question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerFeedback) Reset() {
	*x = AnswerFeedback{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerFeedback) ProtoMessage() {}

func (x *AnswerFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerFeedback.ProtoReflect.Descriptor instead.
func (*AnswerFeedback) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{10}
}

func (x *AnswerFeedback) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AnswerFeedback) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *AnswerFeedback) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *AnswerFeedback) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *AnswerFeedback) GetSuggestions() string {
	if x != nil {
		return x.Suggestions
	}
	return ""
}

func (x *AnswerFeedback) GetFollowUp() string {
	if x != nil {
		return x.FollowUp
	}
	return ""
}

func (x *AnswerFeedback) GetNextQuestion() *InterviewQuestion {
	if x != nil {
		return x.NextQuestion
	}
	return nil
}

type GetNextQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,3,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextQuestionRequest) Reset() {
	*x = GetNextQuestionRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextQuestionRequest) ProtoMessage() {}

func (x *GetNextQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetNextQuestionRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{11}
}

func (x *GetNextQuestionRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *GetNextQuestionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNextQuestionRequest) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

type NextQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *InterviewQuestion     `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextQuestionResponse) Reset() {
	*x = NextQuestionResponse{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextQuestionResponse) ProtoMessage() {}

func (x *NextQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextQuestionResponse.ProtoReflect.Descriptor instead.
func (*NextQuestionResponse) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{12}
}

func (x *NextQuestionResponse) GetQuestion() *InterviewQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *NextQuestionResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type FinishInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishInterviewRequest) Reset() {
	*x = FinishInterviewRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishInterviewRequest) ProtoMessage() {}

func (x *FinishInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishInterviewRequest.ProtoReflect.Descriptor instead.
func (*FinishInterviewRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{13}
}

func (x *FinishInterviewRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *FinishInterviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InterviewReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InterviewId       uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	OverallScore      float64                `protobuf:"fixed64,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	TotalQuestions    int32                  `protobuf:"varint,3,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	CorrectCount      int32                  `protobuf:"varint,4,opt,name=correct_count,json=correctCount,proto3" json:"correct_count,omitempty"`
	DimensionScores   map[string]float64     `protobuf:"bytes,5,rep,name=dimension_scores,json=dimensionScores,proto3" json:"dimension_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Strengths         []string               `protobuf:"bytes,6,rep,name=strengths,proto3" json:"strengths,omitempty"`
	Weaknesses        []string               `protobuf:"bytes,7,rep,name=weaknesses,proto3" json:"weaknesses,omitempty"`
	Suggestions       []string               `protobuf:"bytes,8,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Summary           string                 `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	CodingDiagnostics []*CodingDiagnosis     `protobuf:"bytes,10,rep,name=coding_diagnostics,json=codingDiagnostics,proto3" json:"coding_diagnostics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InterviewReport) Reset() {
	*x = InterviewReport{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewReport) ProtoMessage() {}

func (x *InterviewReport) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewReport.ProtoReflect.Descriptor instead.
func (*InterviewReport) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{14}
}

func (x *InterviewReport) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *InterviewReport) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *InterviewReport) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *InterviewReport) GetCorrectCount() int32 {
	if x != nil {
		return x.CorrectCount
	}
	return 0
}

func (x *InterviewReport) GetDimensionScores() map[string]float64 {
	if x != nil {
		return x.DimensionScores
	}
	return nil
}

func (x *InterviewReport) GetStrengths() []string {
	if x != nil {
		return x.Strengths
	}
	return nil
}

func (x *InterviewReport) GetWeaknesses() []string {
	if x != nil {
		return x.Weaknesses
	}
	return nil
}

func (x *InterviewReport) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *InterviewReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *InterviewReport) GetCodingDiagnostics() []*CodingDiagnosis {
	if x != nil {
		return x.CodingDiagnostics
	}
	return nil
}

type CodingDiagnosis struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuestionIndex   int32                  `protobuf:"varint,1,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Topic           string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Score           float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	MistakeTags     []string               `protobuf:"bytes,5,rep,name=mistake_tags,json=mistakeTags,proto3" json:"mistake_tags,omitempty"`
	StrengthTags    []string               `protobuf:"bytes,6,rep,name=strength_tags,json=strengthTags,proto3" json:"strength_tags,omitempty"`
	EvidenceSummary string                 `protobuf:"bytes,7,opt,name=evidence_summary,json=evidenceSummary,proto3" json:"evidence_summary,omitempty"`
	Suggestions     []string               `protobuf:"bytes,8,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CodingDiagnosis) Reset() {
	*x = CodingDiagnosis{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodingDiagnosis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodingDiagnosis) ProtoMessage() {}

func (x *CodingDiagnosis) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodingDiagnosis.ProtoReflect.Descriptor instead.
func (*CodingDiagnosis) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{15}
}

func (x *CodingDiagnosis) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

func (x *CodingDiagnosis) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CodingDiagnosis) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CodingDiagnosis) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CodingDiagnosis) GetMistakeTags() []string {
	if x != nil {
		return x.MistakeTags
	}
	return nil
}

func (x *CodingDiagnosis) GetStrengthTags() []string {
	if x != nil {
		return x.StrengthTags
	}
	return nil
}

func (x *CodingDiagnosis) GetEvidenceSummary() string {
	if x != nil {
		return x.EvidenceSummary
	}
	return ""
}

func (x *CodingDiagnosis) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type SubmitCodingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionIndex int32                  `protobuf:"varint,3,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCodingRequest) Reset() {
	*x = SubmitCodingRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCodingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCodingRequest) ProtoMessage() {}

func (x *SubmitCodingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCodingRequest.ProtoReflect.Descriptor instead.
func (*SubmitCodingRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitCodingRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *SubmitCodingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitCodingRequest) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

func (x *SubmitCodingRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubmitCodingRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CodingResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Passed          bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	TestCasesPassed int32                  `protobuf:"varint,2,opt,name=test_cases_passed,json=testCasesPassed,proto3" json:"test_cases_passed,omitempty"`
	TotalTestCases  int32                  `protobuf:"varint,3,opt,name=total_test_cases,json=totalTestCases,proto3" json:"total_test_cases,omitempty"`
	Output          string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Feedback        *AnswerFeedback        `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CodingResult) Reset() {
	*x = CodingResult{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodingResult) ProtoMessage() {}

func (x *CodingResult) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodingResult.ProtoReflect.Descriptor instead.
func (*CodingResult) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{17}
}

func (x *CodingResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CodingResult) GetTestCasesPassed() int32 {
	if x != nil {
		return x.TestCasesPassed
	}
	return 0
}

func (x *CodingResult) GetTotalTestCases() int32 {
	if x != nil {
		return x.TotalTestCases
	}
	return 0
}

func (x *CodingResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CodingResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CodingResult) GetFeedback() *AnswerFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type GetInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterviewRequest) Reset() {
	*x = GetInterviewRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterviewRequest) ProtoMessage() {}

func (x *GetInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterviewRequest.ProtoReflect.Descriptor instead.
func (*GetInterviewRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{18}
}

func (x *GetInterviewRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *GetInterviewRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListInterviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *v1.PageParam          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterviewsRequest) Reset() {
	*x = ListInterviewsRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterviewsRequest) ProtoMessage() {}

func (x *ListInterviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterviewsRequest.ProtoReflect.Descriptor instead.
func (*ListInterviewsRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{19}
}

func (x *ListInterviewsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListInterviewsRequest) GetPage() *v1.PageParam {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListInterviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interviews    []*InterviewResponse   `protobuf:"bytes,1,rep,name=interviews,proto3" json:"interviews,omitempty"`
	PageResult    *v1.PageResult         `protobuf:"bytes,2,opt,name=page_result,json=pageResult,proto3" json:"page_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterviewsResponse) Reset() {
	*x = ListInterviewsResponse{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterviewsResponse) ProtoMessage() {}

func (x *ListInterviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterviewsResponse.ProtoReflect.Descriptor instead.
func (*ListInterviewsResponse) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{20}
}

func (x *ListInterviewsResponse) GetInterviews() []*InterviewResponse {
	if x != nil {
		return x.Interviews
	}
	return nil
}

func (x *ListInterviewsResponse) GetPageResult() *v1.PageResult {
	if x != nil {
		return x.PageResult
	}
	return nil
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{21}
}

func (x *GetReportRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *GetReportRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InterviewStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalInterviews        int32                  `protobuf:"varint,1,opt,name=total_interviews,json=totalInterviews,proto3" json:"total_interviews,omitempty"`
	AvgScore               float64                `protobuf:"fixed64,2,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	TotalQuestionsAnswered int32                  `protobuf:"varint,3,opt,name=total_questions_answered,json=totalQuestionsAnswered,proto3" json:"total_questions_answered,omitempty"`
	AvgAccuracy            float64                `protobuf:"fixed64,4,opt,name=avg_accuracy,json=avgAccuracy,proto3" json:"avg_accuracy,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InterviewStats) Reset() {
	*x = InterviewStats{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewStats) ProtoMessage() {}

func (x *InterviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewStats.ProtoReflect.Descriptor instead.
func (*InterviewStats) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{22}
}

func (x *InterviewStats) GetTotalInterviews() int32 {
	if x != nil {
		return x.TotalInterviews
	}
	return 0
}

func (x *InterviewStats) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *InterviewStats) GetTotalQuestionsAnswered() int32 {
	if x != nil {
		return x.TotalQuestionsAnswered
	}
	return 0
}

func (x *InterviewStats) GetAvgAccuracy() float64 {
	if x != nil {
		return x.AvgAccuracy
	}
	return 0
}

type IsRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRealtimeRequest) Reset() {
	*x = IsRealtimeRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRealtimeRequest) ProtoMessage() {}

func (x *IsRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRealtimeRequest.ProtoReflect.Descriptor instead.
func (*IsRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{23}
}

func (x *IsRealtimeRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

type IsRealtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRealtime    bool                   `protobuf:"varint,1,opt,name=is_realtime,json=isRealtime,proto3" json:"is_realtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsRealtimeResponse) Reset() {
	*x = IsRealtimeResponse{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRealtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRealtimeResponse) ProtoMessage() {}

func (x *IsRealtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRealtimeResponse.ProtoReflect.Descriptor instead.
func (*IsRealtimeResponse) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{24}
}

func (x *IsRealtimeResponse) GetIsRealtime() bool {
	if x != nil {
		return x.IsRealtime
	}
	return false
}

type GetRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeRequest) Reset() {
	*x = GetRealtimeRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeRequest) ProtoMessage() {}

func (x *GetRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{25}
}

func (x *GetRealtimeRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *GetRealtimeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RealtimeInterviewContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	IndustryCode  string                 `protobuf:"bytes,2,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	History       []*InterviewMessage    `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	CurrentTopic  string                 `protobuf:"bytes,5,opt,name=current_topic,json=currentTopic,proto3" json:"current_topic,omitempty"`
	QuestionIndex int32                  `protobuf:"varint,6,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeInterviewContext) Reset() {
	*x = RealtimeInterviewContext{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeInterviewContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeInterviewContext) ProtoMessage() {}

func (x *RealtimeInterviewContext) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeInterviewContext.ProtoReflect.Descriptor instead.
func (*RealtimeInterviewContext) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{26}
}

func (x *RealtimeInterviewContext) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *RealtimeInterviewContext) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *RealtimeInterviewContext) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *RealtimeInterviewContext) GetHistory() []*InterviewMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RealtimeInterviewContext) GetCurrentTopic() string {
	if x != nil {
		return x.CurrentTopic
	}
	return ""
}

func (x *RealtimeInterviewContext) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

type BindDialogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	DialogId      string                 `protobuf:"bytes,2,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindDialogRequest) Reset() {
	*x = BindDialogRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindDialogRequest) ProtoMessage() {}

func (x *BindDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindDialogRequest.ProtoReflect.Descriptor instead.
func (*BindDialogRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{27}
}

func (x *BindDialogRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *BindDialogRequest) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

type AppendAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	AnswerText    string                 `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendAnswerRequest) Reset() {
	*x = AppendAnswerRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAnswerRequest) ProtoMessage() {}

func (x *AppendAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAnswerRequest.ProtoReflect.Descriptor instead.
func (*AppendAnswerRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{28}
}

func (x *AppendAnswerRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *AppendAnswerRequest) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

type AppendReplyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InterviewId     uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	ReplyText       string                 `protobuf:"bytes,2,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	Live2DDirective *Live2DDirective       `protobuf:"bytes,3,opt,name=live2d_directive,json=live2dDirective,proto3" json:"live2d_directive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendReplyRequest) Reset() {
	*x = AppendReplyRequest{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendReplyRequest) ProtoMessage() {}

func (x *AppendReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendReplyRequest.ProtoReflect.Descriptor instead.
func (*AppendReplyRequest) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{29}
}

func (x *AppendReplyRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *AppendReplyRequest) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

func (x *AppendReplyRequest) GetLive2DDirective() *Live2DDirective {
	if x != nil {
		return x.Live2DDirective
	}
	return nil
}

type AppendReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldEnd     bool                   `protobuf:"varint,1,opt,name=should_end,json=shouldEnd,proto3" json:"should_end,omitempty"`
	NextQuestion  *InterviewQuestion     `protobuf:"bytes,2,opt,name=next_question,json=nextQuestion,proto3" json:"next_question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendReplyResponse) Reset() {
	*x = AppendReplyResponse{}
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendReplyResponse) ProtoMessage() {}

func (x *AppendReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_interview_v1_interview_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendReplyResponse.ProtoReflect.Descriptor instead.
func (*AppendReplyResponse) Descriptor() ([]byte, []int) {
	return file_makejob_interview_v1_interview_proto_rawDescGZIP(), []int{30}
}

func (x *AppendReplyResponse) GetShouldEnd() bool {
	if x != nil {
		return x.ShouldEnd
	}
	return false
}

func (x *AppendReplyResponse) GetNextQuestion() *InterviewQuestion {
	if x != nil {
		return x.NextQuestion
	}
	return nil
}

var File_makejob_interview_v1_interview_proto protoreflect.FileDescriptor

const file_makejob_interview_v1_interview_proto_rawDesc = "" +
	"\n" +
	"$makejob/interview/v1/interview.proto\x12\x14makejob.interview.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\"makejob/shared/v1/pagination.proto\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xd0\x02\n" +
	"\x16CreateInterviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12#\n" +
	"\rindustry_code\x18\x02 \x01(\tR\findustryCode\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06topics\x18\x04 \x03(\tR\x06topics\x12%\n" +
	"\x0equestion_count\x18\x05 \x01(\x05R\rquestionCount\x12(\n" +
	"\x10live2d_model_key\x18\x06 \x01(\tR\x0elive2dModelKey\x12%\n" +
	"\x0einterview_mode\x18\a \x01(\tR\rinterviewMode\x12\x1f\n" +
	"\vresume_text\x18\b \x01(\tR\n" +
	"resumeText\x12'\n" +
	"\x0fjob_description\x18\t \x01(\tR\x0ejobDescription\"\xc6\x01\n" +
	"\x11InterviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12N\n" +
	"\x0efirst_question\x18\x03 \x01(\v2'.makejob.interview.v1.InterviewQuestionR\rfirstQuestion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdc\x02\n" +
	"\x0fInterviewDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12#\n" +
	"\rindustry_code\x18\x03 \x01(\tR\findustryCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0einterview_mode\x18\x05 \x01(\tR\rinterviewMode\x12B\n" +
	"\bmessages\x18\x06 \x03(\v2&.makejob.interview.v1.InterviewMessageR\bmessages\x12=\n" +
	"\x06report\x18\a \x01(\v2%.makejob.interview.v1.InterviewReportR\x06report\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xae\x01\n" +
	"\x10InterviewMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xea\x02\n" +
	"\x11InterviewQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05hints\x18\x05 \x01(\tR\x05hints\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12!\n" +
	"\fstarter_code\x18\a \x01(\tR\vstarterCode\x12\x1f\n" +
	"\veditor_mode\x18\b \x01(\tR\n" +
	"editorMode\x12'\n" +
	"\x0fevaluation_mode\x18\t \x01(\tR\x0eevaluationMode\x12P\n" +
	"\x10live2d_directive\x18\n" +
	" \x01(\v2%.makejob.interview.v1.Live2DDirectiveR\x0flive2dDirective\"\xbc\x03\n" +
	"\x0fLive2DDirective\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12R\n" +
	"\x0eexpression_mix\x18\x04 \x03(\v2+.makejob.interview.v1.Live2DExpressionLayerR\rexpressionMix\x12^\n" +
	"\x13parameter_overrides\x18\x05 \x03(\v2-.makejob.interview.v1.Live2DParameterOverrideR\x12parameterOverrides\x12\x1d\n" +
	"\n" +
	"motion_key\x18\x06 \x01(\tR\tmotionKey\x12!\n" +
	"\fmotion_group\x18\a \x01(\tR\vmotionGroup\x12,\n" +
	"\x12motion_duration_ms\x18\b \x01(\x05R\x10motionDurationMs\x12\x1c\n" +
	"\tintensity\x18\t \x01(\x01R\tintensity\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x05R\n" +
	"durationMs\"O\n" +
	"\x15Live2DExpressionLayer\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"E\n" +
	"\x17Live2DParameterOverride\x12\x14\n" +
	"\x05param\x18\x01 \x01(\tR\x05param\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xac\x01\n" +
	"\x13SubmitAnswerRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12%\n" +
	"\x0equestion_index\x18\x03 \x01(\x05R\rquestionIndex\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\x8d\x02\n" +
	"\x0eAnswerFeedback\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"key_points\x18\x04 \x03(\tR\tkeyPoints\x12 \n" +
	"\vsuggestions\x18\x05 \x01(\tR\vsuggestions\x12\x1b\n" +
	"\tfollow_up\x18\x06 \x01(\tR\bfollowUp\x12L\n" +
	"\rnext_question\x18\a \x01(\v2'.makejob.interview.v1.InterviewQuestionR\fnextQuestion\"y\n" +
	"\x16GetNextQuestionRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12#\n" +
	"\rcurrent_index\x18\x03 \x01(\x05R\fcurrentIndex\"t\n" +
	"\x14NextQuestionResponse\x12C\n" +
	"\bquestion\x18\x01 \x01(\v2'.makejob.interview.v1.InterviewQuestionR\bquestion\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\"T\n" +
	"\x16FinishInterviewRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\xa2\x04\n" +
	"\x0fInterviewReport\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x01R\foverallScore\x12'\n" +
	"\x0ftotal_questions\x18\x03 \x01(\x05R\x0etotalQuestions\x12#\n" +
	"\rcorrect_count\x18\x04 \x01(\x05R\fcorrectCount\x12e\n" +
	"\x10dimension_scores\x18\x05 \x03(\v2:.makejob.interview.v1.InterviewReport.DimensionScoresEntryR\x0fdimensionScores\x12\x1c\n" +
	"\tstrengths\x18\x06 \x03(\tR\tstrengths\x12\x1e\n" +
	"\n" +
	"weaknesses\x18\a \x03(\tR\n" +
	"weaknesses\x12 \n" +
	"\vsuggestions\x18\b \x03(\tR\vsuggestions\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12T\n" +
	"\x12coding_diagnostics\x18\n" +
	" \x03(\v2%.makejob.interview.v1.CodingDiagnosisR\x11codingDiagnostics\x1aB\n" +
	"\x14DimensionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x95\x02\n" +
	"\x0fCodingDiagnosis\x12%\n" +
	"\x0equestion_index\x18\x01 \x01(\x05R\rquestionIndex\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12!\n" +
	"\fmistake_tags\x18\x05 \x03(\tR\vmistakeTags\x12#\n" +
	"\rstrength_tags\x18\x06 \x03(\tR\fstrengthTags\x12)\n" +
	"\x10evidence_summary\x18\a \x01(\tR\x0fevidenceSummary\x12 \n" +
	"\vsuggestions\x18\b \x03(\tR\vsuggestions\"\xa8\x01\n" +
	"\x13SubmitCodingRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12%\n" +
	"\x0equestion_index\x18\x03 \x01(\x05R\rquestionIndex\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\"\xec\x01\n" +
	"\fCodingResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12*\n" +
	"\x11test_cases_passed\x18\x02 \x01(\x05R\x0ftestCasesPassed\x12(\n" +
	"\x10total_test_cases\x18\x03 \x01(\x05R\x0etotalTestCases\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12@\n" +
	"\bfeedback\x18\x06 \x01(\v2$.makejob.interview.v1.AnswerFeedbackR\bfeedback\"Q\n" +
	"\x13GetInterviewRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"b\n" +
	"\x15ListInterviewsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x120\n" +
	"\x04page\x18\x02 \x01(\v2\x1c.makejob.shared.v1.PageParamR\x04page\"\xa1\x01\n" +
	"\x16ListInterviewsResponse\x12G\n" +
	"\n" +
	"interviews\x18\x01 \x03(\v2'.makejob.interview.v1.InterviewResponseR\n" +
	"interviews\x12>\n" +
	"\vpage_result\x18\x02 \x01(\v2\x1d.makejob.shared.v1.PageResultR\n" +
	"pageResult\"N\n" +
	"\x10GetReportRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\xb5\x01\n" +
	"\x0eInterviewStats\x12)\n" +
	"\x10total_interviews\x18\x01 \x01(\x05R\x0ftotalInterviews\x12\x1b\n" +
	"\tavg_score\x18\x02 \x01(\x01R\bavgScore\x128\n" +
	"\x18total_questions_answered\x18\x03 \x01(\x05R\x16totalQuestionsAnswered\x12!\n" +
	"\favg_accuracy\x18\x04 \x01(\x01R\vavgAccuracy\"6\n" +
	"\x11IsRealtimeRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\"5\n" +
	"\x12IsRealtimeResponse\x12\x1f\n" +
	"\vis_realtime\x18\x01 \x01(\bR\n" +
	"isRealtime\"P\n" +
	"\x12GetRealtimeRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x90\x02\n" +
	"\x18RealtimeInterviewContext\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12#\n" +
	"\rindustry_code\x18\x02 \x01(\tR\findustryCode\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12@\n" +
	"\ahistory\x18\x04 \x03(\v2&.makejob.interview.v1.InterviewMessageR\ahistory\x12#\n" +
	"\rcurrent_topic\x18\x05 \x01(\tR\fcurrentTopic\x12%\n" +
	"\x0equestion_index\x18\x06 \x01(\x05R\rquestionIndex\"S\n" +
	"\x11BindDialogRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x1b\n" +
	"\tdialog_id\x18\x02 \x01(\tR\bdialogId\"Y\n" +
	"\x13AppendAnswerRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x1f\n" +
	"\vanswer_text\x18\x02 \x01(\tR\n" +
	"answerText\"\xa8\x01\n" +
	"\x12AppendReplyRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x02 \x01(\tR\treplyText\x12P\n" +
	"\x10live2d_directive\x18\x03 \x01(\v2%.makejob.interview.v1.Live2DDirectiveR\x0flive2dDirective\"\x82\x01\n" +
	"\x13AppendReplyResponse\x12\x1d\n" +
	"\n" +
	"should_end\x18\x01 \x01(\bR\tshouldEnd\x12L\n" +
	"\rnext_question\x18\x02 \x01(\v2'.makejob.interview.v1.InterviewQuestionR\fnextQuestion2\xa7\v\n" +
	"\x10InterviewService\x12h\n" +
	"\x0fCreateInterview\x12,.makejob.interview.v1.CreateInterviewRequest\x1a'.makejob.interview.v1.InterviewResponse\x12`\n" +
	"\fGetInterview\x12).makejob.interview.v1.GetInterviewRequest\x1a%.makejob.interview.v1.InterviewDetail\x12k\n" +
	"\x0eListInterviews\x12+.makejob.interview.v1.ListInterviewsRequest\x1a,.makejob.interview.v1.ListInterviewsResponse\x12f\n" +
	"\x0fFinishInterview\x12,.makejob.interview.v1.FinishInterviewRequest\x1a%.makejob.interview.v1.InterviewReport\x12_\n" +
	"\fSubmitAnswer\x12).makejob.interview.v1.SubmitAnswerRequest\x1a$.makejob.interview.v1.AnswerFeedback\x12k\n" +
	"\x0fGetNextQuestion\x12,.makejob.interview.v1.GetNextQuestionRequest\x1a*.makejob.interview.v1.NextQuestionResponse\x12h\n" +
	"\x13IsRealtimeInterview\x12'.makejob.interview.v1.IsRealtimeRequest\x1a(.makejob.interview.v1.IsRealtimeResponse\x12n\n" +
	"\x12GetRealtimeContext\x12(.makejob.interview.v1.GetRealtimeRequest\x1a..makejob.interview.v1.RealtimeInterviewContext\x12U\n" +
	"\x12BindRealtimeDialog\x12'.makejob.interview.v1.BindDialogRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x18AppendRealtimeUserAnswer\x12).makejob.interview.v1.AppendAnswerRequest\x1a\x16.google.protobuf.Empty\x12s\n" +
	"\x1cAppendRealtimeAssistantReply\x12(.makejob.interview.v1.AppendReplyRequest\x1a).makejob.interview.v1.AppendReplyResponse\x12c\n" +
	"\x12SubmitCodingAnswer\x12).makejob.interview.v1.SubmitCodingRequest\x1a\".makejob.interview.v1.CodingResult\x12Z\n" +
	"\tGetReport\x12&.makejob.interview.v1.GetReportRequest\x1a%.makejob.interview.v1.InterviewReport\x12^\n" +
	"\x11GetInterviewStats\x12#.makejob.interview.v1.UserIDRequest\x1a$.makejob.interview.v1.InterviewStatsB.Z,makejob/api/makejob/interview/v1;interviewv1b\x06proto3"

var (
	file_makejob_interview_v1_interview_proto_rawDescOnce sync.Once
	file_makejob_interview_v1_interview_proto_rawDescData []byte
)

func file_makejob_interview_v1_interview_proto_rawDescGZIP() []byte {
	file_makejob_interview_v1_interview_proto_rawDescOnce.Do(func() {
		file_makejob_interview_v1_interview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_interview_v1_interview_proto_rawDesc), len(file_makejob_interview_v1_interview_proto_rawDesc)))
	})
	return file_makejob_interview_v1_interview_proto_rawDescData
}

var file_makejob_interview_v1_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_makejob_interview_v1_interview_proto_goTypes = []any{
	(*UserIDRequest)(nil),            // 0: makejob.interview.v1.UserIDRequest
	(*CreateInterviewRequest)(nil),   // 1: makejob.interview.v1.CreateInterviewRequest
	(*InterviewResponse)(nil),        // 2: makejob.interview.v1.InterviewResponse
	(*InterviewDetail)(nil),          // 3: makejob.interview.v1.InterviewDetail
	(*InterviewMessage)(nil),         // 4: makejob.interview.v1.InterviewMessage
	(*InterviewQuestion)(nil),        // 5: makejob.interview.v1.InterviewQuestion
	(*Live2DDirective)(nil),          // 6: makejob.interview.v1.Live2DDirective
	(*Live2DExpressionLayer)(nil),    // 7: makejob.interview.v1.Live2DExpressionLayer
	(*Live2DParameterOverride)(nil),  // 8: makejob.interview.v1.Live2DParameterOverride
	(*SubmitAnswerRequest)(nil),      // 9: makejob.interview.v1.SubmitAnswerRequest
	(*AnswerFeedback)(nil),           // 10: makejob.interview.v1.AnswerFeedback
	(*GetNextQuestionRequest)(nil),   // 11: makejob.interview.v1.GetNextQuestionRequest
	(*NextQuestionResponse)(nil),     // 12: makejob.interview.v1.NextQuestionResponse
	(*FinishInterviewRequest)(nil),   // 13: makejob.interview.v1.FinishInterviewRequest
	(*InterviewReport)(nil),          // 14: makejob.interview.v1.InterviewReport
	(*CodingDiagnosis)(nil),          // 15: makejob.interview.v1.CodingDiagnosis
	(*SubmitCodingRequest)(nil),      // 16: makejob.interview.v1.SubmitCodingRequest
	(*CodingResult)(nil),             // 17: makejob.interview.v1.CodingResult
	(*GetInterviewRequest)(nil),      // 18: makejob.interview.v1.GetInterviewRequest
	(*ListInterviewsRequest)(nil),    // 19: makejob.interview.v1.ListInterviewsRequest
	(*ListInterviewsResponse)(nil),   // 20: makejob.interview.v1.ListInterviewsResponse
	(*GetReportRequest)(nil),         // 21: makejob.interview.v1.GetReportRequest
	(*InterviewStats)(nil),           // 22: makejob.interview.v1.InterviewStats
	(*IsRealtimeRequest)(nil),        // 23: makejob.interview.v1.IsRealtimeRequest
	(*IsRealtimeResponse)(nil),       // 24: makejob.interview.v1.IsRealtimeResponse
	(*GetRealtimeRequest)(nil),       // 25: makejob.interview.v1.GetRealtimeRequest
	(*RealtimeInterviewContext)(nil), // 26: makejob.interview.v1.RealtimeInterviewContext
	(*BindDialogRequest)(nil),        // 27: makejob.interview.v1.BindDialogRequest
	(*AppendAnswerRequest)(nil),      // 28: makejob.interview.v1.AppendAnswerRequest
	(*AppendReplyRequest)(nil),       // 29: makejob.interview.v1.AppendReplyRequest
	(*AppendReplyResponse)(nil),      // 30: makejob.interview.v1.AppendReplyResponse
	nil,                              // 31: makejob.interview.v1.InterviewReport.DimensionScoresEntry
	(*timestamppb.Timestamp)(nil),    // 32: google.protobuf.Timestamp
	(*v1.PageParam)(nil),             // 33: makejob.shared.v1.PageParam
	(*v1.PageResult)(nil),            // 34: makejob.shared.v1.PageResult
	(*emptypb.Empty)(nil),            // 35: google.protobuf.Empty
}
var file_makejob_interview_v1_interview_proto_depIdxs = []int32{
	5,  // 0: makejob.interview.v1.InterviewResponse.first_question:type_name -> makejob.interview.v1.InterviewQuestion
	32, // 1: makejob.interview.v1.InterviewResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 2: makejob.interview.v1.InterviewDetail.messages:type_name -> makejob.interview.v1.InterviewMessage
	14, // 3: makejob.interview.v1.InterviewDetail.report:type_name -> makejob.interview.v1.InterviewReport
	32, // 4: makejob.interview.v1.InterviewDetail.created_at:type_name -> google.protobuf.Timestamp
	32, // 5: makejob.interview.v1.InterviewMessage.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: makejob.interview.v1.InterviewQuestion.live2d_directive:type_name -> makejob.interview.v1.Live2DDirective
	7,  // 7: makejob.interview.v1.Live2DDirective.expression_mix:type_name -> makejob.interview.v1.Live2DExpressionLayer
	8,  // 8: makejob.interview.v1.Live2DDirective.parameter_overrides:type_name -> makejob.interview.v1.Live2DParameterOverride
	5,  // 9: makejob.interview.v1.AnswerFeedback.next_question:type_name -> makejob.interview.v1.InterviewQuestion
	5,  // 10: makejob.interview.v1.NextQuestionResponse.question:type_name -> makejob.interview.v1.InterviewQuestion
	31, // 11: makejob.interview.v1.InterviewReport.dimension_scores:type_name -> makejob.interview.v1.InterviewReport.DimensionScoresEntry
	15, // 12: makejob.interview.v1.InterviewReport.coding_diagnostics:type_name -> makejob.interview.v1.CodingDiagnosis
	10, // 13: makejob.interview.v1.CodingResult.feedback:type_name -> makejob.interview.v1.AnswerFeedback
	33, // 14: makejob.interview.v1.ListInterviewsRequest.page:type_name -> makejob.shared.v1.PageParam
	2,  // 15: makejob.interview.v1.ListInterviewsResponse.interviews:type_name -> makejob.interview.v1.InterviewResponse
	34, // 16: makejob.interview.v1.ListInterviewsResponse.page_result:type_name -> makejob.shared.v1.PageResult
	4,  // 17: makejob.interview.v1.RealtimeInterviewContext.history:type_name -> makejob.interview.v1.InterviewMessage
	6,  // 18: makejob.interview.v1.AppendReplyRequest.live2d_directive:type_name -> makejob.interview.v1.Live2DDirective
	5,  // 19: makejob.interview.v1.AppendReplyResponse.next_question:type_name -> makejob.interview.v1.InterviewQuestion
	1,  // 20: makejob.interview.v1.InterviewService.CreateInterview:input_type -> makejob.interview.v1.CreateInterviewRequest
	18, // 21: makejob.interview.v1.InterviewService.GetInterview:input_type -> makejob.interview.v1.GetInterviewRequest
	19, // 22: makejob.interview.v1.InterviewService.ListInterviews:input_type -> makejob.interview.v1.ListInterviewsRequest
	13, // 23: makejob.interview.v1.InterviewService.FinishInterview:input_type -> makejob.interview.v1.FinishInterviewRequest
	9,  // 24: makejob.interview.v1.InterviewService.SubmitAnswer:input_type -> makejob.interview.v1.SubmitAnswerRequest
	11, // 25: makejob.interview.v1.InterviewService.GetNextQuestion:input_type -> makejob.interview.v1.GetNextQuestionRequest
	23, // 26: makejob.interview.v1.InterviewService.IsRealtimeInterview:input_type -> makejob.interview.v1.IsRealtimeRequest
	25, // 27: makejob.interview.v1.InterviewService.GetRealtimeContext:input_type -> makejob.interview.v1.GetRealtimeRequest
	27, // 28: makejob.interview.v1.InterviewService.BindRealtimeDialog:input_type -> makejob.interview.v1.BindDialogRequest
	28, // 29: makejob.interview.v1.InterviewService.AppendRealtimeUserAnswer:input_type -> makejob.interview.v1.AppendAnswerRequest
	29, // 30: makejob.interview.v1.InterviewService.AppendRealtimeAssistantReply:input_type -> makejob.interview.v1.AppendReplyRequest
	16, // 31: makejob.interview.v1.InterviewService.SubmitCodingAnswer:input_type -> makejob.interview.v1.SubmitCodingRequest
	21, // 32: makejob.interview.v1.InterviewService.GetReport:input_type -> makejob.interview.v1.GetReportRequest
	0,  // 33: makejob.interview.v1.InterviewService.GetInterviewStats:input_type -> makejob.interview.v1.UserIDRequest
	2,  // 34: makejob.interview.v1.InterviewService.CreateInterview:output_type -> makejob.interview.v1.InterviewResponse
	3,  // 35: makejob.interview.v1.InterviewService.GetInterview:output_type -> makejob.interview.v1.InterviewDetail
	20, // 36: makejob.interview.v1.InterviewService.ListInterviews:output_type -> makejob.interview.v1.ListInterviewsResponse
	14, // 37: makejob.interview.v1.InterviewService.FinishInterview:output_type -> makejob.interview.v1.InterviewReport
	10, // 38: makejob.interview.v1.InterviewService.SubmitAnswer:output_type -> makejob.interview.v1.AnswerFeedback
	12, // 39: makejob.interview.v1.InterviewService.GetNextQuestion:output_type -> makejob.interview.v1.NextQuestionResponse
	24, // 40: makejob.interview.v1.InterviewService.IsRealtimeInterview:output_type -> makejob.interview.v1.IsRealtimeResponse
	26, // 41: makejob.interview.v1.InterviewService.GetRealtimeContext:output_type -> makejob.interview.v1.RealtimeInterviewContext
	35, // 42: makejob.interview.v1.InterviewService.BindRealtimeDialog:output_type -> google.protobuf.Empty
	35, // 43: makejob.interview.v1.InterviewService.AppendRealtimeUserAnswer:output_type -> google.protobuf.Empty
	30, // 44: makejob.interview.v1.InterviewService.AppendRealtimeAssistantReply:output_type -> makejob.interview.v1.AppendReplyResponse
	17, // 45: makejob.interview.v1.InterviewService.SubmitCodingAnswer:output_type -> makejob.interview.v1.CodingResult
	14, // 46: makejob.interview.v1.InterviewService.GetReport:output_type -> makejob.interview.v1.InterviewReport
	22, // 47: makejob.interview.v1.InterviewService.GetInterviewStats:output_type -> makejob.interview.v1.InterviewStats
	34, // [34:48] is the sub-list for method output_type
	20, // [20:34] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_makejob_interview_v1_interview_proto_init() }
func file_makejob_interview_v1_interview_proto_init() {
	if File_makejob_interview_v1_interview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_interview_v1_interview_proto_rawDesc), len(file_makejob_interview_v1_interview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_interview_v1_interview_proto_goTypes,
		DependencyIndexes: file_makejob_interview_v1_interview_proto_depIdxs,
		MessageInfos:      file_makejob_interview_v1_interview_proto_msgTypes,
	}.Build()
	File_makejob_interview_v1_interview_proto = out.File
	file_makejob_interview_v1_interview_proto_goTypes = nil
	file_makejob_interview_v1_interview_proto_depIdxs = nil
}
