// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/membership/v1/membership.proto

package membershipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *UserIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MembershipStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Level               string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "free" or "pro"
	ExpireAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	IsActive            bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DailyPracticeLimit  int32                  `protobuf:"varint,4,opt,name=daily_practice_limit,json=dailyPracticeLimit,proto3" json:"daily_practice_limit,omitempty"`    // 每日练习限制
	DailyInterviewLimit int32                  `protobuf:"varint,5,opt,name=daily_interview_limit,json=dailyInterviewLimit,proto3" json:"daily_interview_limit,omitempty"` // 每日面试限制
	PracticeUsedToday   int32                  `protobuf:"varint,6,opt,name=practice_used_today,json=practiceUsedToday,proto3" json:"practice_used_today,omitempty"`       // 今日已练习数
	InterviewUsedToday  int32                  `protobuf:"varint,7,opt,name=interview_used_today,json=interviewUsedToday,proto3" json:"interview_used_today,omitempty"`    // 今日已面试数
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MembershipStatus) Reset() {
	*x = MembershipStatus{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipStatus) ProtoMessage() {}

func (x *MembershipStatus) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipStatus.ProtoReflect.Descriptor instead.
func (*MembershipStatus) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{1}
}

func (x *MembershipStatus) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *MembershipStatus) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *MembershipStatus) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *MembershipStatus) GetDailyPracticeLimit() int32 {
	if x != nil {
		return x.DailyPracticeLimit
	}
	return 0
}

func (x *MembershipStatus) GetDailyInterviewLimit() int32 {
	if x != nil {
		return x.DailyInterviewLimit
	}
	return 0
}

func (x *MembershipStatus) GetPracticeUsedToday() int32 {
	if x != nil {
		return x.PracticeUsedToday
	}
	return 0
}

func (x *MembershipStatus) GetInterviewUsedToday() int32 {
	if x != nil {
		return x.InterviewUsedToday
	}
	return 0
}

type MembershipPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanType      string                 `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"` // monthly/quarterly/yearly
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,4,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Features      []string               `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipPlan) Reset() {
	*x = MembershipPlan{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipPlan) ProtoMessage() {}

func (x *MembershipPlan) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipPlan.ProtoReflect.Descriptor instead.
func (*MembershipPlan) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{2}
}

func (x *MembershipPlan) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *MembershipPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MembershipPlan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MembershipPlan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *MembershipPlan) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{3}
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*MembershipPlan      `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlansResponse) GetPlans() []*MembershipPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanType      string                 `protobuf:"bytes,2,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"` // monthly/quarterly/yearly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PlanType      string                 `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // pending/paid/cancelled/refunded
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{6}
}

func (x *OrderResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderResponse) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *OrderResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderResponse) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *OrderResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse       `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrdersResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentCallbackRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentCallbackRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CheckFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Feature       string                 `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"` // "unlimited_practice", "unlimited_interview"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFeatureRequest) Reset() {
	*x = CheckFeatureRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFeatureRequest) ProtoMessage() {}

func (x *CheckFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFeatureRequest.ProtoReflect.Descriptor instead.
func (*CheckFeatureRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{11}
}

func (x *CheckFeatureRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckFeatureRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

type CheckFeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFeatureResponse) Reset() {
	*x = CheckFeatureResponse{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFeatureResponse) ProtoMessage() {}

func (x *CheckFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFeatureResponse.ProtoReflect.Descriptor instead.
func (*CheckFeatureResponse) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{12}
}

func (x *CheckFeatureResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckFeatureResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	DurationDays  int32                  `protobuf:"varint,3,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeRequest) Reset() {
	*x = UpgradeRequest{}
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeRequest) ProtoMessage() {}

func (x *UpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_membership_v1_membership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeRequest.ProtoReflect.Descriptor instead.
func (*UpgradeRequest) Descriptor() ([]byte, []int) {
	return file_makejob_membership_v1_membership_proto_rawDescGZIP(), []int{13}
}

func (x *UpgradeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpgradeRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

var File_makejob_membership_v1_membership_proto protoreflect.FileDescriptor

const file_makejob_membership_v1_membership_proto_rawDesc = "" +
	"\n" +
	"&makejob/membership/v1/membership.proto\x12\x15makejob.membership.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xc6\x02\n" +
	"\x10MembershipStatus\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x127\n" +
	"\texpire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x120\n" +
	"\x14daily_practice_limit\x18\x04 \x01(\x05R\x12dailyPracticeLimit\x122\n" +
	"\x15daily_interview_limit\x18\x05 \x01(\x05R\x13dailyInterviewLimit\x12.\n" +
	"\x13practice_used_today\x18\x06 \x01(\x05R\x11practiceUsedToday\x120\n" +
	"\x14interview_used_today\x18\a \x01(\x05R\x12interviewUsedToday\"\x98\x01\n" +
	"\x0eMembershipPlan\x12\x1b\n" +
	"\tplan_type\x18\x01 \x01(\tR\bplanType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12#\n" +
	"\rduration_days\x18\x04 \x01(\x05R\fdurationDays\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\tR\bfeatures\"\x12\n" +
	"\x10ListPlansRequest\"P\n" +
	"\x11ListPlansResponse\x12;\n" +
	"\x05plans\x18\x01 \x03(\v2%.makejob.membership.v1.MembershipPlanR\x05plans\"J\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tplan_type\x18\x02 \x01(\tR\bplanType\"\xb2\x02\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tplan_type\x18\x03 \x01(\tR\bplanType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\apaid_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"E\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"]\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"h\n" +
	"\x12ListOrdersResponse\x12<\n" +
	"\x06orders\x18\x01 \x03(\v2$.makejob.membership.v1.OrderResponseR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"t\n" +
	"\x16PaymentCallbackRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"H\n" +
	"\x13CheckFeatureRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\afeature\x18\x02 \x01(\tR\afeature\"H\n" +
	"\x14CheckFeatureResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"d\n" +
	"\x0eUpgradeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12#\n" +
	"\rduration_days\x18\x03 \x01(\x05R\fdurationDays2\xb8\x06\n" +
	"\x11MembershipService\x12d\n" +
	"\x13GetMembershipStatus\x12$.makejob.membership.v1.UserIDRequest\x1a'.makejob.membership.v1.MembershipStatus\x12^\n" +
	"\tListPlans\x12'.makejob.membership.v1.ListPlansRequest\x1a(.makejob.membership.v1.ListPlansResponse\x12^\n" +
	"\vCreateOrder\x12).makejob.membership.v1.CreateOrderRequest\x1a$.makejob.membership.v1.OrderResponse\x12X\n" +
	"\bGetOrder\x12&.makejob.membership.v1.GetOrderRequest\x1a$.makejob.membership.v1.OrderResponse\x12a\n" +
	"\n" +
	"ListOrders\x12(.makejob.membership.v1.ListOrdersRequest\x1a).makejob.membership.v1.ListOrdersResponse\x12l\n" +
	"\x15HandlePaymentCallback\x12-.makejob.membership.v1.PaymentCallbackRequest\x1a$.makejob.membership.v1.OrderResponse\x12m\n" +
	"\x12CheckFeatureAccess\x12*.makejob.membership.v1.CheckFeatureRequest\x1a+.makejob.membership.v1.CheckFeatureResponse\x12c\n" +
	"\x11UpgradeMembership\x12%.makejob.membership.v1.UpgradeRequest\x1a'.makejob.membership.v1.MembershipStatusB0Z.makejob/api/makejob/membership/v1;membershipv1b\x06proto3"

var (
	file_makejob_membership_v1_membership_proto_rawDescOnce sync.Once
	file_makejob_membership_v1_membership_proto_rawDescData []byte
)

func file_makejob_membership_v1_membership_proto_rawDescGZIP() []byte {
	file_makejob_membership_v1_membership_proto_rawDescOnce.Do(func() {
		file_makejob_membership_v1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_membership_v1_membership_proto_rawDesc), len(file_makejob_membership_v1_membership_proto_rawDesc)))
	})
	return file_makejob_membership_v1_membership_proto_rawDescData
}

var file_makejob_membership_v1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_makejob_membership_v1_membership_proto_goTypes = []any{
	(*UserIDRequest)(nil),          // 0: makejob.membership.v1.UserIDRequest
	(*MembershipStatus)(nil),       // 1: makejob.membership.v1.MembershipStatus
	(*MembershipPlan)(nil),         // 2: makejob.membership.v1.MembershipPlan
	(*ListPlansRequest)(nil),       // 3: makejob.membership.v1.ListPlansRequest
	(*ListPlansResponse)(nil),      // 4: makejob.membership.v1.ListPlansResponse
	(*CreateOrderRequest)(nil),     // 5: makejob.membership.v1.CreateOrderRequest
	(*OrderResponse)(nil),          // 6: makejob.membership.v1.OrderResponse
	(*GetOrderRequest)(nil),        // 7: makejob.membership.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),      // 8: makejob.membership.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),     // 9: makejob.membership.v1.ListOrdersResponse
	(*PaymentCallbackRequest)(nil), // 10: makejob.membership.v1.PaymentCallbackRequest
	(*CheckFeatureRequest)(nil),    // 11: makejob.membership.v1.CheckFeatureRequest
	(*CheckFeatureResponse)(nil),   // 12: makejob.membership.v1.CheckFeatureResponse
	(*UpgradeRequest)(nil),         // 13: makejob.membership.v1.UpgradeRequest
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_makejob_membership_v1_membership_proto_depIdxs = []int32{
	14, // 0: makejob.membership.v1.MembershipStatus.expire_at:type_name -> google.protobuf.Timestamp
	2,  // 1: makejob.membership.v1.ListPlansResponse.plans:type_name -> makejob.membership.v1.MembershipPlan
	14, // 2: makejob.membership.v1.OrderResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: makejob.membership.v1.OrderResponse.paid_at:type_name -> google.protobuf.Timestamp
	14, // 4: makejob.membership.v1.OrderResponse.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 5: makejob.membership.v1.ListOrdersResponse.orders:type_name -> makejob.membership.v1.OrderResponse
	0,  // 6: makejob.membership.v1.MembershipService.GetMembershipStatus:input_type -> makejob.membership.v1.UserIDRequest
	3,  // 7: makejob.membership.v1.MembershipService.ListPlans:input_type -> makejob.membership.v1.ListPlansRequest
	5,  // 8: makejob.membership.v1.MembershipService.CreateOrder:input_type -> makejob.membership.v1.CreateOrderRequest
	7,  // 9: makejob.membership.v1.MembershipService.GetOrder:input_type -> makejob.membership.v1.GetOrderRequest
	8,  // 10: makejob.membership.v1.MembershipService.ListOrders:input_type -> makejob.membership.v1.ListOrdersRequest
	10, // 11: makejob.membership.v1.MembershipService.HandlePaymentCallback:input_type -> makejob.membership.v1.PaymentCallbackRequest
	11, // 12: makejob.membership.v1.MembershipService.CheckFeatureAccess:input_type -> makejob.membership.v1.CheckFeatureRequest
	13, // 13: makejob.membership.v1.MembershipService.UpgradeMembership:input_type -> makejob.membership.v1.UpgradeRequest
	1,  // 14: makejob.membership.v1.MembershipService.GetMembershipStatus:output_type -> makejob.membership.v1.MembershipStatus
	4,  // 15: makejob.membership.v1.MembershipService.ListPlans:output_type -> makejob.membership.v1.ListPlansResponse
	6,  // 16: makejob.membership.v1.MembershipService.CreateOrder:output_type -> makejob.membership.v1.OrderResponse
	6,  // 17: makejob.membership.v1.MembershipService.GetOrder:output_type -> makejob.membership.v1.OrderResponse
	9,  // 18: makejob.membership.v1.MembershipService.ListOrders:output_type -> makejob.membership.v1.ListOrdersResponse
	6,  // 19: makejob.membership.v1.MembershipService.HandlePaymentCallback:output_type -> makejob.membership.v1.OrderResponse
	12, // 20: makejob.membership.v1.MembershipService.CheckFeatureAccess:output_type -> makejob.membership.v1.CheckFeatureResponse
	1,  // 21: makejob.membership.v1.MembershipService.UpgradeMembership:output_type -> makejob.membership.v1.MembershipStatus
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_makejob_membership_v1_membership_proto_init() }
func file_makejob_membership_v1_membership_proto_init() {
	if File_makejob_membership_v1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_membership_v1_membership_proto_rawDesc), len(file_makejob_membership_v1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_membership_v1_membership_proto_goTypes,
		DependencyIndexes: file_makejob_membership_v1_membership_proto_depIdxs,
		MessageInfos:      file_makejob_membership_v1_membership_proto_msgTypes,
	}.Build()
	File_makejob_membership_v1_membership_proto = out.File
	file_makejob_membership_v1_membership_proto_goTypes = nil
	file_makejob_membership_v1_membership_proto_depIdxs = nil
}
