// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/realtime/v1/realtime.proto

package realtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSessionRequest) Reset() {
	*x = InitSessionRequest{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSessionRequest) ProtoMessage() {}

func (x *InitSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSessionRequest.ProtoReflect.Descriptor instead.
func (*InitSessionRequest) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *InitSessionRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *InitSessionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WsUrl         string                 `protobuf:"bytes,3,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *SessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type InjectRAGContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRAGContextRequest) Reset() {
	*x = InjectRAGContextRequest{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRAGContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRAGContextRequest) ProtoMessage() {}

func (x *InjectRAGContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRAGContextRequest.ProtoReflect.Descriptor instead.
func (*InjectRAGContextRequest) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *InjectRAGContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InjectRAGContextRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type InjectRAGContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRAGContextResponse) Reset() {
	*x = InjectRAGContextResponse{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRAGContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRAGContextResponse) ProtoMessage() {}

func (x *InjectRAGContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRAGContextResponse.ProtoReflect.Descriptor instead.
func (*InjectRAGContextResponse) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *InjectRAGContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{6}
}

func (x *EndSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_realtime_v1_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_makejob_realtime_v1_realtime_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_makejob_realtime_v1_realtime_proto protoreflect.FileDescriptor

const file_makejob_realtime_v1_realtime_proto_rawDesc = "" +
	"\n" +
	"\"makejob/realtime/v1/realtime.proto\x12\x13makejob.realtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x12InitSessionRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x9a\x01\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x15\n" +
	"\x06ws_url\x18\x03 \x01(\tR\x05wsUrl\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"8\n" +
	"\x17GetSessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"R\n" +
	"\x17InjectRAGContextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"4\n" +
	"\x18InjectRAGContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x89\x04\n" +
	"\x0fRealtimeService\x12\\\n" +
	"\vInitSession\x12'.makejob.realtime.v1.InitSessionRequest\x1a$.makejob.realtime.v1.SessionResponse\x12f\n" +
	"\x10GetSessionStatus\x12,.makejob.realtime.v1.GetSessionStatusRequest\x1a$.makejob.realtime.v1.SessionResponse\x12o\n" +
	"\x10InjectRAGContext\x12,.makejob.realtime.v1.InjectRAGContextRequest\x1a-.makejob.realtime.v1.InjectRAGContextResponse\x12]\n" +
	"\n" +
	"EndSession\x12&.makejob.realtime.v1.EndSessionRequest\x1a'.makejob.realtime.v1.EndSessionResponse\x12`\n" +
	"\vHealthCheck\x12'.makejob.realtime.v1.HealthCheckRequest\x1a(.makejob.realtime.v1.HealthCheckResponseB,Z*makejob/api/makejob/realtime/v1;realtimev1b\x06proto3"

var (
	file_makejob_realtime_v1_realtime_proto_rawDescOnce sync.Once
	file_makejob_realtime_v1_realtime_proto_rawDescData []byte
)

func file_makejob_realtime_v1_realtime_proto_rawDescGZIP() []byte {
	file_makejob_realtime_v1_realtime_proto_rawDescOnce.Do(func() {
		file_makejob_realtime_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_realtime_v1_realtime_proto_rawDesc), len(file_makejob_realtime_v1_realtime_proto_rawDesc)))
	})
	return file_makejob_realtime_v1_realtime_proto_rawDescData
}

var file_makejob_realtime_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_makejob_realtime_v1_realtime_proto_goTypes = []any{
	(*InitSessionRequest)(nil),       // 0: makejob.realtime.v1.InitSessionRequest
	(*SessionResponse)(nil),          // 1: makejob.realtime.v1.SessionResponse
	(*GetSessionStatusRequest)(nil),  // 2: makejob.realtime.v1.GetSessionStatusRequest
	(*InjectRAGContextRequest)(nil),  // 3: makejob.realtime.v1.InjectRAGContextRequest
	(*InjectRAGContextResponse)(nil), // 4: makejob.realtime.v1.InjectRAGContextResponse
	(*EndSessionRequest)(nil),        // 5: makejob.realtime.v1.EndSessionRequest
	(*EndSessionResponse)(nil),       // 6: makejob.realtime.v1.EndSessionResponse
	(*HealthCheckRequest)(nil),       // 7: makejob.realtime.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 8: makejob.realtime.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_makejob_realtime_v1_realtime_proto_depIdxs = []int32{
	9, // 0: makejob.realtime.v1.SessionResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: makejob.realtime.v1.RealtimeService.InitSession:input_type -> makejob.realtime.v1.InitSessionRequest
	2, // 2: makejob.realtime.v1.RealtimeService.GetSessionStatus:input_type -> makejob.realtime.v1.GetSessionStatusRequest
	3, // 3: makejob.realtime.v1.RealtimeService.InjectRAGContext:input_type -> makejob.realtime.v1.InjectRAGContextRequest
	5, // 4: makejob.realtime.v1.RealtimeService.EndSession:input_type -> makejob.realtime.v1.EndSessionRequest
	7, // 5: makejob.realtime.v1.RealtimeService.HealthCheck:input_type -> makejob.realtime.v1.HealthCheckRequest
	1, // 6: makejob.realtime.v1.RealtimeService.InitSession:output_type -> makejob.realtime.v1.SessionResponse
	1, // 7: makejob.realtime.v1.RealtimeService.GetSessionStatus:output_type -> makejob.realtime.v1.SessionResponse
	4, // 8: makejob.realtime.v1.RealtimeService.InjectRAGContext:output_type -> makejob.realtime.v1.InjectRAGContextResponse
	6, // 9: makejob.realtime.v1.RealtimeService.EndSession:output_type -> makejob.realtime.v1.EndSessionResponse
	8, // 10: makejob.realtime.v1.RealtimeService.HealthCheck:output_type -> makejob.realtime.v1.HealthCheckResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_makejob_realtime_v1_realtime_proto_init() }
func file_makejob_realtime_v1_realtime_proto_init() {
	if File_makejob_realtime_v1_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_realtime_v1_realtime_proto_rawDesc), len(file_makejob_realtime_v1_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_realtime_v1_realtime_proto_goTypes,
		DependencyIndexes: file_makejob_realtime_v1_realtime_proto_depIdxs,
		MessageInfos:      file_makejob_realtime_v1_realtime_proto_msgTypes,
	}.Build()
	File_makejob_realtime_v1_realtime_proto = out.File
	file_makejob_realtime_v1_realtime_proto_goTypes = nil
	file_makejob_realtime_v1_realtime_proto_depIdxs = nil
}
