// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: makejob/growth/v1/growth.proto

package growthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrowthService_GetGrowthSummary_FullMethodName = "/makejob.growth.v1.GrowthService/GetGrowthSummary"
	GrowthService_GetWeeklyFocus_FullMethodName   = "/makejob.growth.v1.GrowthService/GetWeeklyFocus"
	GrowthService_SyncStudyLog_FullMethodName     = "/makejob.growth.v1.GrowthService/SyncStudyLog"
)

// GrowthServiceClient is the client API for GrowthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrowthServiceClient interface {
	GetGrowthSummary(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*GrowthSummary, error)
	GetWeeklyFocus(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*WeeklyFocus, error)
	SyncStudyLog(ctx context.Context, in *SyncStudyLogRequest, opts ...grpc.CallOption) (*StudyLog, error)
}

type growthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrowthServiceClient(cc grpc.ClientConnInterface) GrowthServiceClient {
	return &growthServiceClient{cc}
}

func (c *growthServiceClient) GetGrowthSummary(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*GrowthSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrowthSummary)
	err := c.cc.Invoke(ctx, GrowthService_GetGrowthSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growthServiceClient) GetWeeklyFocus(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*WeeklyFocus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeeklyFocus)
	err := c.cc.Invoke(ctx, GrowthService_GetWeeklyFocus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *growthServiceClient) SyncStudyLog(ctx context.Context, in *SyncStudyLogRequest, opts ...grpc.CallOption) (*StudyLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudyLog)
	err := c.cc.Invoke(ctx, GrowthService_SyncStudyLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrowthServiceServer is the server API for GrowthService service.
// All implementations must embed UnimplementedGrowthServiceServer
// for forward compatibility.
type GrowthServiceServer interface {
	GetGrowthSummary(context.Context, *UserIDRequest) (*GrowthSummary, error)
	GetWeeklyFocus(context.Context, *UserIDRequest) (*WeeklyFocus, error)
	SyncStudyLog(context.Context, *SyncStudyLogRequest) (*StudyLog, error)
	mustEmbedUnimplementedGrowthServiceServer()
}

// UnimplementedGrowthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrowthServiceServer struct{}

func (UnimplementedGrowthServiceServer) GetGrowthSummary(context.Context, *UserIDRequest) (*GrowthSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrowthSummary not implemented")
}
func (UnimplementedGrowthServiceServer) GetWeeklyFocus(context.Context, *UserIDRequest) (*WeeklyFocus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyFocus not implemented")
}
func (UnimplementedGrowthServiceServer) SyncStudyLog(context.Context, *SyncStudyLogRequest) (*StudyLog, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncStudyLog not implemented")
}
func (UnimplementedGrowthServiceServer) mustEmbedUnimplementedGrowthServiceServer() {}
func (UnimplementedGrowthServiceServer) testEmbeddedByValue()                       {}

// UnsafeGrowthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrowthServiceServer will
// result in compilation errors.
type UnsafeGrowthServiceServer interface {
	mustEmbedUnimplementedGrowthServiceServer()
}

func RegisterGrowthServiceServer(s grpc.ServiceRegistrar, srv GrowthServiceServer) {
	// If the following call panics, it indicates UnimplementedGrowthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrowthService_ServiceDesc, srv)
}

func _GrowthService_GetGrowthSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowthServiceServer).GetGrowthSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrowthService_GetGrowthSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowthServiceServer).GetGrowthSummary(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrowthService_GetWeeklyFocus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowthServiceServer).GetWeeklyFocus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrowthService_GetWeeklyFocus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowthServiceServer).GetWeeklyFocus(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrowthService_SyncStudyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStudyLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrowthServiceServer).SyncStudyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrowthService_SyncStudyLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrowthServiceServer).SyncStudyLog(ctx, req.(*SyncStudyLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrowthService_ServiceDesc is the grpc.ServiceDesc for GrowthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrowthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "makejob.growth.v1.GrowthService",
	HandlerType: (*GrowthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGrowthSummary",
			Handler:    _GrowthService_GetGrowthSummary_Handler,
		},
		{
			MethodName: "GetWeeklyFocus",
			Handler:    _GrowthService_GetWeeklyFocus_Handler,
		},
		{
			MethodName: "SyncStudyLog",
			Handler:    _GrowthService_SyncStudyLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "makejob/growth/v1/growth.proto",
}
