server:
  http:
    addr: 0.0.0.0:8080
    timeout: 10s

services:
  user:
    addr: "localhost:9001"
  membership:
    addr: "localhost:9002"
  question:
    addr: "localhost:9003"
  interview:
    addr: "localhost:9004"
  realtime:
    addr: "localhost:8085"
  growth:
    addr: "localhost:9006"
  plan:
    addr: "localhost:9007"
  companion:
    addr: "localhost:9008"
  community:
    addr: "localhost:9009"
  admin:
    addr: "localhost:9014"

jwt:
  secret: "makejob-secret-key-change-in-production"
