// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: makejob/industry/v1/industry.proto

package industryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIndustryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndustryRequest) Reset() {
	*x = GetIndustryRequest{}
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndustryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndustryRequest) ProtoMessage() {}

func (x *GetIndustryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndustryRequest.ProtoReflect.Descriptor instead.
func (*GetIndustryRequest) Descriptor() ([]byte, []int) {
	return file_makejob_industry_v1_industry_proto_rawDescGZIP(), []int{0}
}

func (x *GetIndustryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListIndustriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Industries    []*Industry            `protobuf:"bytes,1,rep,name=industries,proto3" json:"industries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndustriesResponse) Reset() {
	*x = ListIndustriesResponse{}
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndustriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndustriesResponse) ProtoMessage() {}

func (x *ListIndustriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndustriesResponse.ProtoReflect.Descriptor instead.
func (*ListIndustriesResponse) Descriptor() ([]byte, []int) {
	return file_makejob_industry_v1_industry_proto_rawDescGZIP(), []int{1}
}

func (x *ListIndustriesResponse) GetIndustries() []*Industry {
	if x != nil {
		return x.Industries
	}
	return nil
}

type Industry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Industry) Reset() {
	*x = Industry{}
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Industry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Industry) ProtoMessage() {}

func (x *Industry) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Industry.ProtoReflect.Descriptor instead.
func (*Industry) Descriptor() ([]byte, []int) {
	return file_makejob_industry_v1_industry_proto_rawDescGZIP(), []int{2}
}

func (x *Industry) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Industry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Industry) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Industry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateIndustryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndustryRequest) Reset() {
	*x = CreateIndustryRequest{}
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndustryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndustryRequest) ProtoMessage() {}

func (x *CreateIndustryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndustryRequest.ProtoReflect.Descriptor instead.
func (*CreateIndustryRequest) Descriptor() ([]byte, []int) {
	return file_makejob_industry_v1_industry_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIndustryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateIndustryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIndustryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateIndustryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateIndustryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIndustryRequest) Reset() {
	*x = UpdateIndustryRequest{}
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIndustryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIndustryRequest) ProtoMessage() {}

func (x *UpdateIndustryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_industry_v1_industry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIndustryRequest.ProtoReflect.Descriptor instead.
func (*UpdateIndustryRequest) Descriptor() ([]byte, []int) {
	return file_makejob_industry_v1_industry_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIndustryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateIndustryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateIndustryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateIndustryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_makejob_industry_v1_industry_proto protoreflect.FileDescriptor

const file_makejob_industry_v1_industry_proto_rawDesc = "" +
	"\n" +
	"\"makejob/industry/v1/industry.proto\x12\x13makejob.industry.v1\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x12GetIndustryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"W\n" +
	"\x16ListIndustriesResponse\x12=\n" +
	"\n" +
	"industries\x18\x01 \x03(\v2\x1d.makejob.industry.v1.IndustryR\n" +
	"industries\"h\n" +
	"\bIndustry\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"u\n" +
	"\x15CreateIndustryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"u\n" +
	"\x15UpdateIndustryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription2\xf9\x02\n" +
	"\x0fIndustryService\x12U\n" +
	"\x0eListIndustries\x12\x16.google.protobuf.Empty\x1a+.makejob.industry.v1.ListIndustriesResponse\x12U\n" +
	"\vGetIndustry\x12'.makejob.industry.v1.GetIndustryRequest\x1a\x1d.makejob.industry.v1.Industry\x12[\n" +
	"\x0eCreateIndustry\x12*.makejob.industry.v1.CreateIndustryRequest\x1a\x1d.makejob.industry.v1.Industry\x12[\n" +
	"\x0eUpdateIndustry\x12*.makejob.industry.v1.UpdateIndustryRequest\x1a\x1d.makejob.industry.v1.IndustryB,Z*makejob/api/makejob/industry/v1;industryv1b\x06proto3"

var (
	file_makejob_industry_v1_industry_proto_rawDescOnce sync.Once
	file_makejob_industry_v1_industry_proto_rawDescData []byte
)

func file_makejob_industry_v1_industry_proto_rawDescGZIP() []byte {
	file_makejob_industry_v1_industry_proto_rawDescOnce.Do(func() {
		file_makejob_industry_v1_industry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_industry_v1_industry_proto_rawDesc), len(file_makejob_industry_v1_industry_proto_rawDesc)))
	})
	return file_makejob_industry_v1_industry_proto_rawDescData
}

var file_makejob_industry_v1_industry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_makejob_industry_v1_industry_proto_goTypes = []any{
	(*GetIndustryRequest)(nil),     // 0: makejob.industry.v1.GetIndustryRequest
	(*ListIndustriesResponse)(nil), // 1: makejob.industry.v1.ListIndustriesResponse
	(*Industry)(nil),               // 2: makejob.industry.v1.Industry
	(*CreateIndustryRequest)(nil),  // 3: makejob.industry.v1.CreateIndustryRequest
	(*UpdateIndustryRequest)(nil),  // 4: makejob.industry.v1.UpdateIndustryRequest
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_makejob_industry_v1_industry_proto_depIdxs = []int32{
	2, // 0: makejob.industry.v1.ListIndustriesResponse.industries:type_name -> makejob.industry.v1.Industry
	5, // 1: makejob.industry.v1.IndustryService.ListIndustries:input_type -> google.protobuf.Empty
	0, // 2: makejob.industry.v1.IndustryService.GetIndustry:input_type -> makejob.industry.v1.GetIndustryRequest
	3, // 3: makejob.industry.v1.IndustryService.CreateIndustry:input_type -> makejob.industry.v1.CreateIndustryRequest
	4, // 4: makejob.industry.v1.IndustryService.UpdateIndustry:input_type -> makejob.industry.v1.UpdateIndustryRequest
	1, // 5: makejob.industry.v1.IndustryService.ListIndustries:output_type -> makejob.industry.v1.ListIndustriesResponse
	2, // 6: makejob.industry.v1.IndustryService.GetIndustry:output_type -> makejob.industry.v1.Industry
	2, // 7: makejob.industry.v1.IndustryService.CreateIndustry:output_type -> makejob.industry.v1.Industry
	2, // 8: makejob.industry.v1.IndustryService.UpdateIndustry:output_type -> makejob.industry.v1.Industry
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_makejob_industry_v1_industry_proto_init() }
func file_makejob_industry_v1_industry_proto_init() {
	if File_makejob_industry_v1_industry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_industry_v1_industry_proto_rawDesc), len(file_makejob_industry_v1_industry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_industry_v1_industry_proto_goTypes,
		DependencyIndexes: file_makejob_industry_v1_industry_proto_depIdxs,
		MessageInfos:      file_makejob_industry_v1_industry_proto_msgTypes,
	}.Build()
	File_makejob_industry_v1_industry_proto = out.File
	file_makejob_industry_v1_industry_proto_goTypes = nil
	file_makejob_industry_v1_industry_proto_depIdxs = nil
}
