// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: makejob/companion/v1/companion.proto

package companionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompanionService_Chat_FullMethodName              = "/makejob.companion.v1.CompanionService/Chat"
	CompanionService_GetCompanionState_FullMethodName = "/makejob.companion.v1.CompanionService/GetCompanionState"
	CompanionService_SynthesizeSpeech_FullMethodName  = "/makejob.companion.v1.CompanionService/SynthesizeSpeech"
)

// CompanionServiceClient is the client API for CompanionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanionServiceClient interface {
	Chat(ctx context.Context, in *CompanionChatRequest, opts ...grpc.CallOption) (*CompanionChatResponse, error)
	GetCompanionState(ctx context.Context, in *GetCompanionStateRequest, opts ...grpc.CallOption) (*CompanionState, error)
	SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error)
}

type companionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanionServiceClient(cc grpc.ClientConnInterface) CompanionServiceClient {
	return &companionServiceClient{cc}
}

func (c *companionServiceClient) Chat(ctx context.Context, in *CompanionChatRequest, opts ...grpc.CallOption) (*CompanionChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanionChatResponse)
	err := c.cc.Invoke(ctx, CompanionService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionServiceClient) GetCompanionState(ctx context.Context, in *GetCompanionStateRequest, opts ...grpc.CallOption) (*CompanionState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanionState)
	err := c.cc.Invoke(ctx, CompanionService_GetCompanionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companionServiceClient) SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (*SynthesizeSpeechResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeSpeechResponse)
	err := c.cc.Invoke(ctx, CompanionService_SynthesizeSpeech_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanionServiceServer is the server API for CompanionService service.
// All implementations must embed UnimplementedCompanionServiceServer
// for forward compatibility.
type CompanionServiceServer interface {
	Chat(context.Context, *CompanionChatRequest) (*CompanionChatResponse, error)
	GetCompanionState(context.Context, *GetCompanionStateRequest) (*CompanionState, error)
	SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error)
	mustEmbedUnimplementedCompanionServiceServer()
}

// UnimplementedCompanionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompanionServiceServer struct{}

func (UnimplementedCompanionServiceServer) Chat(context.Context, *CompanionChatRequest) (*CompanionChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedCompanionServiceServer) GetCompanionState(context.Context, *GetCompanionStateRequest) (*CompanionState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanionState not implemented")
}
func (UnimplementedCompanionServiceServer) SynthesizeSpeech(context.Context, *SynthesizeSpeechRequest) (*SynthesizeSpeechResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SynthesizeSpeech not implemented")
}
func (UnimplementedCompanionServiceServer) mustEmbedUnimplementedCompanionServiceServer() {}
func (UnimplementedCompanionServiceServer) testEmbeddedByValue()                          {}

// UnsafeCompanionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanionServiceServer will
// result in compilation errors.
type UnsafeCompanionServiceServer interface {
	mustEmbedUnimplementedCompanionServiceServer()
}

func RegisterCompanionServiceServer(s grpc.ServiceRegistrar, srv CompanionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompanionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompanionService_ServiceDesc, srv)
}

func _CompanionService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanionChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanionService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServiceServer).Chat(ctx, req.(*CompanionChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanionService_GetCompanionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServiceServer).GetCompanionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanionService_GetCompanionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServiceServer).GetCompanionState(ctx, req.(*GetCompanionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanionService_SynthesizeSpeech_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanionServiceServer).SynthesizeSpeech(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanionService_SynthesizeSpeech_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanionServiceServer).SynthesizeSpeech(ctx, req.(*SynthesizeSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompanionService_ServiceDesc is the grpc.ServiceDesc for CompanionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompanionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "makejob.companion.v1.CompanionService",
	HandlerType: (*CompanionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _CompanionService_Chat_Handler,
		},
		{
			MethodName: "GetCompanionState",
			Handler:    _CompanionService_GetCompanionState_Handler,
		},
		{
			MethodName: "SynthesizeSpeech",
			Handler:    _CompanionService_SynthesizeSpeech_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "makejob/companion/v1/companion.proto",
}
