// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/companion/v1/companion.proto

package companionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanionChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ContextType   string                 `protobuf:"bytes,3,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionChatRequest) Reset() {
	*x = CompanionChatRequest{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionChatRequest) ProtoMessage() {}

func (x *CompanionChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionChatRequest.ProtoReflect.Descriptor instead.
func (*CompanionChatRequest) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{0}
}

func (x *CompanionChatRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompanionChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanionChatRequest) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

type CompanionChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Emotion       string                 `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Suggestions   []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionChatResponse) Reset() {
	*x = CompanionChatResponse{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionChatResponse) ProtoMessage() {}

func (x *CompanionChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionChatResponse.ProtoReflect.Descriptor instead.
func (*CompanionChatResponse) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{1}
}

func (x *CompanionChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *CompanionChatResponse) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *CompanionChatResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type GetCompanionStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionStateRequest) Reset() {
	*x = GetCompanionStateRequest{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionStateRequest) ProtoMessage() {}

func (x *GetCompanionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionStateRequest.ProtoReflect.Descriptor instead.
func (*GetCompanionStateRequest) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompanionStateRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CompanionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	LastTopic     string                 `protobuf:"bytes,2,opt,name=last_topic,json=lastTopic,proto3" json:"last_topic,omitempty"`
	LastActiveAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionState) Reset() {
	*x = CompanionState{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionState) ProtoMessage() {}

func (x *CompanionState) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionState.ProtoReflect.Descriptor instead.
func (*CompanionState) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{3}
}

func (x *CompanionState) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *CompanionState) GetLastTopic() string {
	if x != nil {
		return x.LastTopic
	}
	return ""
}

func (x *CompanionState) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

type SynthesizeSpeechRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSpeechRequest) Reset() {
	*x = SynthesizeSpeechRequest{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechRequest) ProtoMessage() {}

func (x *SynthesizeSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechRequest) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{4}
}

func (x *SynthesizeSpeechRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeSpeechRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

type SynthesizeSpeechResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,2,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeSpeechResponse) Reset() {
	*x = SynthesizeSpeechResponse{}
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeSpeechResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeSpeechResponse) ProtoMessage() {}

func (x *SynthesizeSpeechResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_companion_v1_companion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeSpeechResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeSpeechResponse) Descriptor() ([]byte, []int) {
	return file_makejob_companion_v1_companion_proto_rawDescGZIP(), []int{5}
}

func (x *SynthesizeSpeechResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SynthesizeSpeechResponse) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

var File_makejob_companion_v1_companion_proto protoreflect.FileDescriptor

const file_makejob_companion_v1_companion_proto_rawDesc = "" +
	"\n" +
	"$makejob/companion/v1/companion.proto\x12\x14makejob.companion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x14CompanionChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcontext_type\x18\x03 \x01(\tR\vcontextType\"i\n" +
	"\x15CompanionChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x18\n" +
	"\aemotion\x18\x02 \x01(\tR\aemotion\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\"3\n" +
	"\x18GetCompanionStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x8b\x01\n" +
	"\x0eCompanionState\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x1d\n" +
	"\n" +
	"last_topic\x18\x02 \x01(\tR\tlastTopic\x12@\n" +
	"\x0elast_active_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\"C\n" +
	"\x17SynthesizeSpeechRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\"V\n" +
	"\x18SynthesizeSpeechResponse\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1b\n" +
	"\taudio_url\x18\x02 \x01(\tR\baudioUrl2\xd1\x02\n" +
	"\x10CompanionService\x12_\n" +
	"\x04Chat\x12*.makejob.companion.v1.CompanionChatRequest\x1a+.makejob.companion.v1.CompanionChatResponse\x12i\n" +
	"\x11GetCompanionState\x12..makejob.companion.v1.GetCompanionStateRequest\x1a$.makejob.companion.v1.CompanionState\x12q\n" +
	"\x10SynthesizeSpeech\x12-.makejob.companion.v1.SynthesizeSpeechRequest\x1a..makejob.companion.v1.SynthesizeSpeechResponseB.Z,makejob/api/makejob/companion/v1;companionv1b\x06proto3"

var (
	file_makejob_companion_v1_companion_proto_rawDescOnce sync.Once
	file_makejob_companion_v1_companion_proto_rawDescData []byte
)

func file_makejob_companion_v1_companion_proto_rawDescGZIP() []byte {
	file_makejob_companion_v1_companion_proto_rawDescOnce.Do(func() {
		file_makejob_companion_v1_companion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_companion_v1_companion_proto_rawDesc), len(file_makejob_companion_v1_companion_proto_rawDesc)))
	})
	return file_makejob_companion_v1_companion_proto_rawDescData
}

var file_makejob_companion_v1_companion_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_makejob_companion_v1_companion_proto_goTypes = []any{
	(*CompanionChatRequest)(nil),     // 0: makejob.companion.v1.CompanionChatRequest
	(*CompanionChatResponse)(nil),    // 1: makejob.companion.v1.CompanionChatResponse
	(*GetCompanionStateRequest)(nil), // 2: makejob.companion.v1.GetCompanionStateRequest
	(*CompanionState)(nil),           // 3: makejob.companion.v1.CompanionState
	(*SynthesizeSpeechRequest)(nil),  // 4: makejob.companion.v1.SynthesizeSpeechRequest
	(*SynthesizeSpeechResponse)(nil), // 5: makejob.companion.v1.SynthesizeSpeechResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_makejob_companion_v1_companion_proto_depIdxs = []int32{
	6, // 0: makejob.companion.v1.CompanionState.last_active_at:type_name -> google.protobuf.Timestamp
	0, // 1: makejob.companion.v1.CompanionService.Chat:input_type -> makejob.companion.v1.CompanionChatRequest
	2, // 2: makejob.companion.v1.CompanionService.GetCompanionState:input_type -> makejob.companion.v1.GetCompanionStateRequest
	4, // 3: makejob.companion.v1.CompanionService.SynthesizeSpeech:input_type -> makejob.companion.v1.SynthesizeSpeechRequest
	1, // 4: makejob.companion.v1.CompanionService.Chat:output_type -> makejob.companion.v1.CompanionChatResponse
	3, // 5: makejob.companion.v1.CompanionService.GetCompanionState:output_type -> makejob.companion.v1.CompanionState
	5, // 6: makejob.companion.v1.CompanionService.SynthesizeSpeech:output_type -> makejob.companion.v1.SynthesizeSpeechResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_makejob_companion_v1_companion_proto_init() }
func file_makejob_companion_v1_companion_proto_init() {
	if File_makejob_companion_v1_companion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_companion_v1_companion_proto_rawDesc), len(file_makejob_companion_v1_companion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_companion_v1_companion_proto_goTypes,
		DependencyIndexes: file_makejob_companion_v1_companion_proto_depIdxs,
		MessageInfos:      file_makejob_companion_v1_companion_proto_msgTypes,
	}.Build()
	File_makejob_companion_v1_companion_proto = out.File
	file_makejob_companion_v1_companion_proto_goTypes = nil
	file_makejob_companion_v1_companion_proto_depIdxs = nil
}
