// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/shared/v1/error.proto

package sharedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                ErrorCode = 0
	ErrorCode_BAD_REQUEST       ErrorCode = 400
	ErrorCode_UNAUTHORIZED      ErrorCode = 401
	ErrorCode_FORBIDDEN         ErrorCode = 403
	ErrorCode_NOT_FOUND         ErrorCode = 404
	ErrorCode_CONFLICT          ErrorCode = 409
	ErrorCode_INTERNAL          ErrorCode = 500
	ErrorCode_TOO_MANY_REQUESTS ErrorCode = 429
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "OK",
		400: "BAD_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		409: "CONFLICT",
		500: "INTERNAL",
		429: "TOO_MANY_REQUESTS",
	}
	ErrorCode_value = map[string]int32{
		"OK":                0,
		"BAD_REQUEST":       400,
		"UNAUTHORIZED":      401,
		"FORBIDDEN":         403,
		"NOT_FOUND":         404,
		"CONFLICT":          409,
		"INTERNAL":          500,
		"TOO_MANY_REQUESTS": 429,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_makejob_shared_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_makejob_shared_v1_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_makejob_shared_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_makejob_shared_v1_error_proto protoreflect.FileDescriptor

const file_makejob_shared_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x1dmakejob/shared/v1/error.proto\x12\x11makejob.shared.v1*\x8e\x01\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\r\n" +
	"\bINTERNAL\x10\xf4\x03\x12\x16\n" +
	"\x11TOO_MANY_REQUESTS\x10\xad\x03B(Z&makejob/api/makejob/shared/v1;sharedv1b\x06proto3"

var (
	file_makejob_shared_v1_error_proto_rawDescOnce sync.Once
	file_makejob_shared_v1_error_proto_rawDescData []byte
)

func file_makejob_shared_v1_error_proto_rawDescGZIP() []byte {
	file_makejob_shared_v1_error_proto_rawDescOnce.Do(func() {
		file_makejob_shared_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_shared_v1_error_proto_rawDesc), len(file_makejob_shared_v1_error_proto_rawDesc)))
	})
	return file_makejob_shared_v1_error_proto_rawDescData
}

var file_makejob_shared_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_makejob_shared_v1_error_proto_goTypes = []any{
	(ErrorCode)(0), // 0: makejob.shared.v1.ErrorCode
}
var file_makejob_shared_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_makejob_shared_v1_error_proto_init() }
func file_makejob_shared_v1_error_proto_init() {
	if File_makejob_shared_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_shared_v1_error_proto_rawDesc), len(file_makejob_shared_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_makejob_shared_v1_error_proto_goTypes,
		DependencyIndexes: file_makejob_shared_v1_error_proto_depIdxs,
		EnumInfos:         file_makejob_shared_v1_error_proto_enumTypes,
	}.Build()
	File_makejob_shared_v1_error_proto = out.File
	file_makejob_shared_v1_error_proto_goTypes = nil
	file_makejob_shared_v1_error_proto_depIdxs = nil
}
