server:
  http:
    addr: 0.0.0.0:8010
  grpc:
    addr: 0.0.0.0:9010

data:
  database:
    driver: postgres
    source: "host=localhost port=5434 user=postgres password=password dbname=makejob sslmode=disable"

jwt:
  secret: "makejob-secret-key-change-in-production"

mq:
  url: "amqp://makejob:makejob123@localhost:5672//makejob"
  exchange: "makejob.events"
