// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/ai/v1/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterviewAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterviewId    uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	IndustryCode   string                 `protobuf:"bytes,2,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Difficulty     string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	History        []*Message             `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	UserAnswer     string                 `protobuf:"bytes,5,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	QuestionIndex  int32                  `protobuf:"varint,6,opt,name=question_index,json=questionIndex,proto3" json:"question_index,omitempty"`
	ResumeText     string                 `protobuf:"bytes,7,opt,name=resume_text,json=resumeText,proto3" json:"resume_text,omitempty"`
	JobDescription string                 `protobuf:"bytes,8,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterviewAgentRequest) Reset() {
	*x = InterviewAgentRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewAgentRequest) ProtoMessage() {}

func (x *InterviewAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewAgentRequest.ProtoReflect.Descriptor instead.
func (*InterviewAgentRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *InterviewAgentRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *InterviewAgentRequest) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *InterviewAgentRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *InterviewAgentRequest) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *InterviewAgentRequest) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *InterviewAgentRequest) GetQuestionIndex() int32 {
	if x != nil {
		return x.QuestionIndex
	}
	return 0
}

func (x *InterviewAgentRequest) GetResumeText() string {
	if x != nil {
		return x.ResumeText
	}
	return ""
}

func (x *InterviewAgentRequest) GetJobDescription() string {
	if x != nil {
		return x.JobDescription
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InterviewAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Hints         string                 `protobuf:"bytes,5,opt,name=hints,proto3" json:"hints,omitempty"`
	Feedback      string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	ShouldEnd     bool                   `protobuf:"varint,8,opt,name=should_end,json=shouldEnd,proto3" json:"should_end,omitempty"`
	Live2DEmotion string                 `protobuf:"bytes,9,opt,name=live2d_emotion,json=live2dEmotion,proto3" json:"live2d_emotion,omitempty"`
	Live2DAction  string                 `protobuf:"bytes,10,opt,name=live2d_action,json=live2dAction,proto3" json:"live2d_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterviewAgentResponse) Reset() {
	*x = InterviewAgentResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewAgentResponse) ProtoMessage() {}

func (x *InterviewAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewAgentResponse.ProtoReflect.Descriptor instead.
func (*InterviewAgentResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *InterviewAgentResponse) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *InterviewAgentResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InterviewAgentResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *InterviewAgentResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InterviewAgentResponse) GetHints() string {
	if x != nil {
		return x.Hints
	}
	return ""
}

func (x *InterviewAgentResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *InterviewAgentResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *InterviewAgentResponse) GetShouldEnd() bool {
	if x != nil {
		return x.ShouldEnd
	}
	return false
}

func (x *InterviewAgentResponse) GetLive2DEmotion() string {
	if x != nil {
		return x.Live2DEmotion
	}
	return ""
}

func (x *InterviewAgentResponse) GetLive2DAction() string {
	if x != nil {
		return x.Live2DAction
	}
	return ""
}

type PlanAgentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IndustryCode     string                 `protobuf:"bytes,2,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Goal             string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	DailyHours       int32                  `protobuf:"varint,4,opt,name=daily_hours,json=dailyHours,proto3" json:"daily_hours,omitempty"`
	WeakTopics       []string               `protobuf:"bytes,5,rep,name=weak_topics,json=weakTopics,proto3" json:"weak_topics,omitempty"`
	RecentActivities []string               `protobuf:"bytes,6,rep,name=recent_activities,json=recentActivities,proto3" json:"recent_activities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanAgentRequest) Reset() {
	*x = PlanAgentRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanAgentRequest) ProtoMessage() {}

func (x *PlanAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanAgentRequest.ProtoReflect.Descriptor instead.
func (*PlanAgentRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *PlanAgentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlanAgentRequest) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *PlanAgentRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *PlanAgentRequest) GetDailyHours() int32 {
	if x != nil {
		return x.DailyHours
	}
	return 0
}

func (x *PlanAgentRequest) GetWeakTopics() []string {
	if x != nil {
		return x.WeakTopics
	}
	return nil
}

func (x *PlanAgentRequest) GetRecentActivities() []string {
	if x != nil {
		return x.RecentActivities
	}
	return nil
}

type PlanAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanTitle     string                 `protobuf:"bytes,1,opt,name=plan_title,json=planTitle,proto3" json:"plan_title,omitempty"`
	Tasks         []*PlanTask            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanAgentResponse) Reset() {
	*x = PlanAgentResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanAgentResponse) ProtoMessage() {}

func (x *PlanAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanAgentResponse.ProtoReflect.Descriptor instead.
func (*PlanAgentResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *PlanAgentResponse) GetPlanTitle() string {
	if x != nil {
		return x.PlanTitle
	}
	return ""
}

func (x *PlanAgentResponse) GetTasks() []*PlanTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *PlanAgentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type PlanTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Phase          string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	OrderIndex     int32                  `protobuf:"varint,4,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	EstimatedHours int32                  `protobuf:"varint,5,opt,name=estimated_hours,json=estimatedHours,proto3" json:"estimated_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanTask) Reset() {
	*x = PlanTask{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanTask) ProtoMessage() {}

func (x *PlanTask) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanTask.ProtoReflect.Descriptor instead.
func (*PlanTask) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{5}
}

func (x *PlanTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlanTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanTask) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PlanTask) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *PlanTask) GetEstimatedHours() int32 {
	if x != nil {
		return x.EstimatedHours
	}
	return 0
}

type CompanionAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ContextType   string                 `protobuf:"bytes,3,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`
	RecentTopics  []string               `protobuf:"bytes,4,rep,name=recent_topics,json=recentTopics,proto3" json:"recent_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionAgentRequest) Reset() {
	*x = CompanionAgentRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionAgentRequest) ProtoMessage() {}

func (x *CompanionAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionAgentRequest.ProtoReflect.Descriptor instead.
func (*CompanionAgentRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{6}
}

func (x *CompanionAgentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompanionAgentRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanionAgentRequest) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

func (x *CompanionAgentRequest) GetRecentTopics() []string {
	if x != nil {
		return x.RecentTopics
	}
	return nil
}

type CompanionAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Emotion       string                 `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Suggestions   []string               `protobuf:"bytes,3,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionAgentResponse) Reset() {
	*x = CompanionAgentResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionAgentResponse) ProtoMessage() {}

func (x *CompanionAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionAgentResponse.ProtoReflect.Descriptor instead.
func (*CompanionAgentResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{7}
}

func (x *CompanionAgentResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *CompanionAgentResponse) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *CompanionAgentResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type QuizAnalyzerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	QuestionType  string                 `protobuf:"bytes,5,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizAnalyzerRequest) Reset() {
	*x = QuizAnalyzerRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnalyzerRequest) ProtoMessage() {}

func (x *QuizAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*QuizAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{8}
}

func (x *QuizAnalyzerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QuizAnalyzerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuizAnalyzerRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QuizAnalyzerRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *QuizAnalyzerRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

type QuizAnalyzerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,4,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	Suggestions   string                 `protobuf:"bytes,5,opt,name=suggestions,proto3" json:"suggestions,omitempty"`
	CorrectAnswer string                 `protobuf:"bytes,6,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizAnalyzerResponse) Reset() {
	*x = QuizAnalyzerResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnalyzerResponse) ProtoMessage() {}

func (x *QuizAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*QuizAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{9}
}

func (x *QuizAnalyzerResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizAnalyzerResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuizAnalyzerResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *QuizAnalyzerResponse) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *QuizAnalyzerResponse) GetSuggestions() string {
	if x != nil {
		return x.Suggestions
	}
	return ""
}

func (x *QuizAnalyzerResponse) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

type ResumeParserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeText    string                 `protobuf:"bytes,1,opt,name=resume_text,json=resumeText,proto3" json:"resume_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeParserRequest) Reset() {
	*x = ResumeParserRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeParserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeParserRequest) ProtoMessage() {}

func (x *ResumeParserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeParserRequest.ProtoReflect.Descriptor instead.
func (*ResumeParserRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeParserRequest) GetResumeText() string {
	if x != nil {
		return x.ResumeText
	}
	return ""
}

type ResumeParserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []string               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	Experience    []string               `protobuf:"bytes,2,rep,name=experience,proto3" json:"experience,omitempty"`
	Education     []string               `protobuf:"bytes,3,rep,name=education,proto3" json:"education,omitempty"`
	Projects      []string               `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeParserResponse) Reset() {
	*x = ResumeParserResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeParserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeParserResponse) ProtoMessage() {}

func (x *ResumeParserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeParserResponse.ProtoReflect.Descriptor instead.
func (*ResumeParserResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeParserResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeParserResponse) GetExperience() []string {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *ResumeParserResponse) GetEducation() []string {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ResumeParserResponse) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ResumeParserResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type Live2DDirectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	EmotionHint   string                 `protobuf:"bytes,2,opt,name=emotion_hint,json=emotionHint,proto3" json:"emotion_hint,omitempty"`
	ReplyText     string                 `protobuf:"bytes,3,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live2DDirectiveRequest) Reset() {
	*x = Live2DDirectiveRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live2DDirectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live2DDirectiveRequest) ProtoMessage() {}

func (x *Live2DDirectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live2DDirectiveRequest.ProtoReflect.Descriptor instead.
func (*Live2DDirectiveRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{12}
}

func (x *Live2DDirectiveRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Live2DDirectiveRequest) GetEmotionHint() string {
	if x != nil {
		return x.EmotionHint
	}
	return ""
}

func (x *Live2DDirectiveRequest) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

type Live2DDirectiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Reply         string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	MotionKey     string                 `protobuf:"bytes,4,opt,name=motion_key,json=motionKey,proto3" json:"motion_key,omitempty"`
	MotionGroup   string                 `protobuf:"bytes,5,opt,name=motion_group,json=motionGroup,proto3" json:"motion_group,omitempty"`
	DurationMs    int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live2DDirectiveResponse) Reset() {
	*x = Live2DDirectiveResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live2DDirectiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live2DDirectiveResponse) ProtoMessage() {}

func (x *Live2DDirectiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live2DDirectiveResponse.ProtoReflect.Descriptor instead.
func (*Live2DDirectiveResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{13}
}

func (x *Live2DDirectiveResponse) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *Live2DDirectiveResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Live2DDirectiveResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *Live2DDirectiveResponse) GetMotionKey() string {
	if x != nil {
		return x.MotionKey
	}
	return ""
}

func (x *Live2DDirectiveResponse) GetMotionGroup() string {
	if x != nil {
		return x.MotionGroup
	}
	return ""
}

func (x *Live2DDirectiveResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RenderPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scene         string                 `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`                                                                                   // 场景标识，如 interview_agent
	TemplateText  string                 `protobuf:"bytes,2,opt,name=template_text,json=templateText,proto3" json:"template_text,omitempty"`                                                 // 模板原文（可选，为空时从DB加载）
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 变量键值对
	RunWithLlm    bool                   `protobuf:"varint,4,opt,name=run_with_llm,json=runWithLlm,proto3" json:"run_with_llm,omitempty"`                                                    // 是否用渲染后的 prompt 调用 LLM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPromptRequest) Reset() {
	*x = RenderPromptRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPromptRequest) ProtoMessage() {}

func (x *RenderPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPromptRequest.ProtoReflect.Descriptor instead.
func (*RenderPromptRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{14}
}

func (x *RenderPromptRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *RenderPromptRequest) GetTemplateText() string {
	if x != nil {
		return x.TemplateText
	}
	return ""
}

func (x *RenderPromptRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *RenderPromptRequest) GetRunWithLlm() bool {
	if x != nil {
		return x.RunWithLlm
	}
	return false
}

type RenderPromptResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RenderedPrompt    string                 `protobuf:"bytes,1,opt,name=rendered_prompt,json=renderedPrompt,proto3" json:"rendered_prompt,omitempty"`                                                                                    // 渲染后的 prompt
	ResolvedVariables map[string]string      `protobuf:"bytes,2,rep,name=resolved_variables,json=resolvedVariables,proto3" json:"resolved_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 解析后的变量明细
	LlmResponse       string                 `protobuf:"bytes,3,opt,name=llm_response,json=llmResponse,proto3" json:"llm_response,omitempty"`                                                                                             // LLM 响应（仅 run_with_llm=true 时有值）
	Model             string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                                                                                                                            // 使用的模型
	LatencyMs         int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                                                                                                  // LLM 调用耗时（仅 run_with_llm=true）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RenderPromptResponse) Reset() {
	*x = RenderPromptResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPromptResponse) ProtoMessage() {}

func (x *RenderPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPromptResponse.ProtoReflect.Descriptor instead.
func (*RenderPromptResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{15}
}

func (x *RenderPromptResponse) GetRenderedPrompt() string {
	if x != nil {
		return x.RenderedPrompt
	}
	return ""
}

func (x *RenderPromptResponse) GetResolvedVariables() map[string]string {
	if x != nil {
		return x.ResolvedVariables
	}
	return nil
}

func (x *RenderPromptResponse) GetLlmResponse() string {
	if x != nil {
		return x.LlmResponse
	}
	return ""
}

func (x *RenderPromptResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RenderPromptResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type DebugAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scene         string                 `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`                                                                             // 场景标识
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                           // 直接传入 prompt 文本
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 变量参数
	ModelOverride string                 `protobuf:"bytes,4,opt,name=model_override,json=modelOverride,proto3" json:"model_override,omitempty"`                                        // 模型覆盖（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugAIRequest) Reset() {
	*x = DebugAIRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugAIRequest) ProtoMessage() {}

func (x *DebugAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugAIRequest.ProtoReflect.Descriptor instead.
func (*DebugAIRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{16}
}

func (x *DebugAIRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *DebugAIRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *DebugAIRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DebugAIRequest) GetModelOverride() string {
	if x != nil {
		return x.ModelOverride
	}
	return ""
}

type DebugAIResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RenderedPrompt string                 `protobuf:"bytes,1,opt,name=rendered_prompt,json=renderedPrompt,proto3" json:"rendered_prompt,omitempty"` // 渲染后的 prompt
	Response       string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`                                   // LLM 原始响应
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                         // 使用的模型
	InputTokens    int32                  `protobuf:"varint,4,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`         // 输入 token 数
	OutputTokens   int32                  `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`      // 输出 token 数
	LatencyMs      int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`               // 调用耗时
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                         // 错误信息（如有）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DebugAIResponse) Reset() {
	*x = DebugAIResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugAIResponse) ProtoMessage() {}

func (x *DebugAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugAIResponse.ProtoReflect.Descriptor instead.
func (*DebugAIResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{17}
}

func (x *DebugAIResponse) GetRenderedPrompt() string {
	if x != nil {
		return x.RenderedPrompt
	}
	return ""
}

func (x *DebugAIResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *DebugAIResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DebugAIResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *DebugAIResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *DebugAIResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DebugAIResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateQuestionCandidatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IndustryCode     string                 `protobuf:"bytes,1,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`              // 行业编码
	Requirement      string                 `protobuf:"bytes,2,opt,name=requirement,proto3" json:"requirement,omitempty"`                                    // 生成需求描述
	CandidateCount   int32                  `protobuf:"varint,3,opt,name=candidate_count,json=candidateCount,proto3" json:"candidate_count,omitempty"`       // 候选题数量
	GenerationMode   string                 `protobuf:"bytes,4,opt,name=generation_mode,json=generationMode,proto3" json:"generation_mode,omitempty"`        // 生成模式
	Sources          []string               `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`                                            // 数据源
	AgentPrompt      string                 `protobuf:"bytes,6,opt,name=agent_prompt,json=agentPrompt,proto3" json:"agent_prompt,omitempty"`                 // 自定义 agent prompt
	IncludeScraped   bool                   `protobuf:"varint,7,opt,name=include_scraped,json=includeScraped,proto3" json:"include_scraped,omitempty"`       // 是否包含爬虫数据
	IncludeGenerated bool                   `protobuf:"varint,8,opt,name=include_generated,json=includeGenerated,proto3" json:"include_generated,omitempty"` // 是否包含 AI 生成数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateQuestionCandidatesRequest) Reset() {
	*x = GenerateQuestionCandidatesRequest{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionCandidatesRequest) ProtoMessage() {}

func (x *GenerateQuestionCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateQuestionCandidatesRequest) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *GenerateQuestionCandidatesRequest) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *GenerateQuestionCandidatesRequest) GetCandidateCount() int32 {
	if x != nil {
		return x.CandidateCount
	}
	return 0
}

func (x *GenerateQuestionCandidatesRequest) GetGenerationMode() string {
	if x != nil {
		return x.GenerationMode
	}
	return ""
}

func (x *GenerateQuestionCandidatesRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GenerateQuestionCandidatesRequest) GetAgentPrompt() string {
	if x != nil {
		return x.AgentPrompt
	}
	return ""
}

func (x *GenerateQuestionCandidatesRequest) GetIncludeScraped() bool {
	if x != nil {
		return x.IncludeScraped
	}
	return false
}

func (x *GenerateQuestionCandidatesRequest) GetIncludeGenerated() bool {
	if x != nil {
		return x.IncludeGenerated
	}
	return false
}

type GenerateQuestionCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndustryCode  string                 `protobuf:"bytes,1,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	Requirement   string                 `protobuf:"bytes,2,opt,name=requirement,proto3" json:"requirement,omitempty"`
	Candidates    []*QuestionCandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Warnings      []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionCandidatesResponse) Reset() {
	*x = GenerateQuestionCandidatesResponse{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionCandidatesResponse) ProtoMessage() {}

func (x *GenerateQuestionCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateQuestionCandidatesResponse) GetIndustryCode() string {
	if x != nil {
		return x.IndustryCode
	}
	return ""
}

func (x *GenerateQuestionCandidatesResponse) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *GenerateQuestionCandidatesResponse) GetCandidates() []*QuestionCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GenerateQuestionCandidatesResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type QuestionCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Answer        string                 `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,7,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	SourceType    string                 `protobuf:"bytes,9,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Solution      string                 `protobuf:"bytes,11,opt,name=solution,proto3" json:"solution,omitempty"`
	JudgeConfig   string                 `protobuf:"bytes,12,opt,name=judge_config,json=judgeConfig,proto3" json:"judge_config,omitempty"`
	SourceLabel   string                 `protobuf:"bytes,13,opt,name=source_label,json=sourceLabel,proto3" json:"source_label,omitempty"`
	SourceTitle   string                 `protobuf:"bytes,14,opt,name=source_title,json=sourceTitle,proto3" json:"source_title,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,15,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionCandidate) Reset() {
	*x = QuestionCandidate{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionCandidate) ProtoMessage() {}

func (x *QuestionCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionCandidate.ProtoReflect.Descriptor instead.
func (*QuestionCandidate) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{20}
}

func (x *QuestionCandidate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionCandidate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QuestionCandidate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuestionCandidate) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *QuestionCandidate) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QuestionCandidate) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuestionCandidate) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *QuestionCandidate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QuestionCandidate) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *QuestionCandidate) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *QuestionCandidate) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *QuestionCandidate) GetJudgeConfig() string {
	if x != nil {
		return x.JudgeConfig
	}
	return ""
}

func (x *QuestionCandidate) GetSourceLabel() string {
	if x != nil {
		return x.SourceLabel
	}
	return ""
}

func (x *QuestionCandidate) GetSourceTitle() string {
	if x != nil {
		return x.SourceTitle
	}
	return ""
}

func (x *QuestionCandidate) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

// 题目流水线流式事件
type QuestionPipelineStreamEvent struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	Event               string                              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`                                   // status | warning | card | complete | error
	Message             string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // 消息文本
	TraceId             string                              `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                // 追踪ID
	RawOutput           string                              `protobuf:"bytes,4,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`          // 原始输出
	FailureStage        string                              `protobuf:"bytes,5,opt,name=failure_stage,json=failureStage,proto3" json:"failure_stage,omitempty"` // 失败阶段
	CandidateExcerpt    string                              `protobuf:"bytes,6,opt,name=candidate_excerpt,json=candidateExcerpt,proto3" json:"candidate_excerpt,omitempty"`
	RepairAttempted     bool                                `protobuf:"varint,7,opt,name=repair_attempted,json=repairAttempted,proto3" json:"repair_attempted,omitempty"`
	SupplementAttempted bool                                `protobuf:"varint,8,opt,name=supplement_attempted,json=supplementAttempted,proto3" json:"supplement_attempted,omitempty"`
	SlotIndex           int32                               `protobuf:"varint,9,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`     // 题卡索引
	RetryIndex          int32                               `protobuf:"varint,10,opt,name=retry_index,json=retryIndex,proto3" json:"retry_index,omitempty"` // 重试索引
	Card                *QuestionCandidate                  `protobuf:"bytes,11,opt,name=card,proto3" json:"card,omitempty"`                                // 题卡数据
	Response            *GenerateQuestionCandidatesResponse `protobuf:"bytes,12,opt,name=response,proto3" json:"response,omitempty"`                        // 完整响应
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QuestionPipelineStreamEvent) Reset() {
	*x = QuestionPipelineStreamEvent{}
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionPipelineStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionPipelineStreamEvent) ProtoMessage() {}

func (x *QuestionPipelineStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_ai_v1_ai_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionPipelineStreamEvent.ProtoReflect.Descriptor instead.
func (*QuestionPipelineStreamEvent) Descriptor() ([]byte, []int) {
	return file_makejob_ai_v1_ai_proto_rawDescGZIP(), []int{21}
}

func (x *QuestionPipelineStreamEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetRawOutput() string {
	if x != nil {
		return x.RawOutput
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetFailureStage() string {
	if x != nil {
		return x.FailureStage
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetCandidateExcerpt() string {
	if x != nil {
		return x.CandidateExcerpt
	}
	return ""
}

func (x *QuestionPipelineStreamEvent) GetRepairAttempted() bool {
	if x != nil {
		return x.RepairAttempted
	}
	return false
}

func (x *QuestionPipelineStreamEvent) GetSupplementAttempted() bool {
	if x != nil {
		return x.SupplementAttempted
	}
	return false
}

func (x *QuestionPipelineStreamEvent) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *QuestionPipelineStreamEvent) GetRetryIndex() int32 {
	if x != nil {
		return x.RetryIndex
	}
	return 0
}

func (x *QuestionPipelineStreamEvent) GetCard() *QuestionCandidate {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *QuestionPipelineStreamEvent) GetResponse() *GenerateQuestionCandidatesResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_makejob_ai_v1_ai_proto protoreflect.FileDescriptor

const file_makejob_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x16makejob/ai/v1/ai.proto\x12\rmakejob.ai.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xc3\x02\n" +
	"\x15InterviewAgentRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\x12#\n" +
	"\rindustry_code\x18\x02 \x01(\tR\findustryCode\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x120\n" +
	"\ahistory\x18\x04 \x03(\v2\x16.makejob.ai.v1.MessageR\ahistory\x12\x1f\n" +
	"\vuser_answer\x18\x05 \x01(\tR\n" +
	"userAnswer\x12%\n" +
	"\x0equestion_index\x18\x06 \x01(\x05R\rquestionIndex\x12\x1f\n" +
	"\vresume_text\x18\a \x01(\tR\n" +
	"resumeText\x12'\n" +
	"\x0fjob_description\x18\b \x01(\tR\x0ejobDescription\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb1\x02\n" +
	"\x16InterviewAgentResponse\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05hints\x18\x05 \x01(\tR\x05hints\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedback\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"should_end\x18\b \x01(\bR\tshouldEnd\x12%\n" +
	"\x0elive2d_emotion\x18\t \x01(\tR\rlive2dEmotion\x12#\n" +
	"\rlive2d_action\x18\n" +
	" \x01(\tR\flive2dAction\"\xd3\x01\n" +
	"\x10PlanAgentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12#\n" +
	"\rindustry_code\x18\x02 \x01(\tR\findustryCode\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x1f\n" +
	"\vdaily_hours\x18\x04 \x01(\x05R\n" +
	"dailyHours\x12\x1f\n" +
	"\vweak_topics\x18\x05 \x03(\tR\n" +
	"weakTopics\x12+\n" +
	"\x11recent_activities\x18\x06 \x03(\tR\x10recentActivities\"{\n" +
	"\x11PlanAgentResponse\x12\x1d\n" +
	"\n" +
	"plan_title\x18\x01 \x01(\tR\tplanTitle\x12-\n" +
	"\x05tasks\x18\x02 \x03(\v2\x17.makejob.ai.v1.PlanTaskR\x05tasks\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\xa2\x01\n" +
	"\bPlanTask\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x1f\n" +
	"\vorder_index\x18\x04 \x01(\x05R\n" +
	"orderIndex\x12'\n" +
	"\x0festimated_hours\x18\x05 \x01(\x05R\x0eestimatedHours\"\x92\x01\n" +
	"\x15CompanionAgentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcontext_type\x18\x03 \x01(\tR\vcontextType\x12#\n" +
	"\rrecent_topics\x18\x04 \x03(\tR\frecentTopics\"j\n" +
	"\x16CompanionAgentResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x18\n" +
	"\aemotion\x18\x02 \x01(\tR\aemotion\x12 \n" +
	"\vsuggestions\x18\x03 \x03(\tR\vsuggestions\"\xa4\x01\n" +
	"\x13QuizAnalyzerRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12#\n" +
	"\rquestion_type\x18\x05 \x01(\tR\fquestionType\"\xcf\x01\n" +
	"\x14QuizAnalyzerResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"key_points\x18\x04 \x03(\tR\tkeyPoints\x12 \n" +
	"\vsuggestions\x18\x05 \x01(\tR\vsuggestions\x12%\n" +
	"\x0ecorrect_answer\x18\x06 \x01(\tR\rcorrectAnswer\"6\n" +
	"\x13ResumeParserRequest\x12\x1f\n" +
	"\vresume_text\x18\x01 \x01(\tR\n" +
	"resumeText\"\xa2\x01\n" +
	"\x14ResumeParserResponse\x12\x16\n" +
	"\x06skills\x18\x01 \x03(\tR\x06skills\x12\x1e\n" +
	"\n" +
	"experience\x18\x02 \x03(\tR\n" +
	"experience\x12\x1c\n" +
	"\teducation\x18\x03 \x03(\tR\teducation\x12\x1a\n" +
	"\bprojects\x18\x04 \x03(\tR\bprojects\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"t\n" +
	"\x16Live2DDirectiveRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12!\n" +
	"\femotion_hint\x18\x02 \x01(\tR\vemotionHint\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x03 \x01(\tR\treplyText\"\xc4\x01\n" +
	"\x17Live2DDirectiveResponse\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"motion_key\x18\x04 \x01(\tR\tmotionKey\x12!\n" +
	"\fmotion_group\x18\x05 \x01(\tR\vmotionGroup\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\"\x81\x02\n" +
	"\x13RenderPromptRequest\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\tR\x05scene\x12#\n" +
	"\rtemplate_text\x18\x02 \x01(\tR\ftemplateText\x12O\n" +
	"\tvariables\x18\x03 \x03(\v21.makejob.ai.v1.RenderPromptRequest.VariablesEntryR\tvariables\x12 \n" +
	"\frun_with_llm\x18\x04 \x01(\bR\n" +
	"runWithLlm\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x02\n" +
	"\x14RenderPromptResponse\x12'\n" +
	"\x0frendered_prompt\x18\x01 \x01(\tR\x0erenderedPrompt\x12i\n" +
	"\x12resolved_variables\x18\x02 \x03(\v2:.makejob.ai.v1.RenderPromptResponse.ResolvedVariablesEntryR\x11resolvedVariables\x12!\n" +
	"\fllm_response\x18\x03 \x01(\tR\vllmResponse\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x1aD\n" +
	"\x16ResolvedVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x0eDebugAIRequest\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\tR\x05scene\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12A\n" +
	"\x06params\x18\x03 \x03(\v2).makejob.ai.v1.DebugAIRequest.ParamsEntryR\x06params\x12%\n" +
	"\x0emodel_override\x18\x04 \x01(\tR\rmodelOverride\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x0fDebugAIResponse\x12'\n" +
	"\x0frendered_prompt\x18\x01 \x01(\tR\x0erenderedPrompt\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x04 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x05R\foutputTokens\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xcf\x02\n" +
	"!GenerateQuestionCandidatesRequest\x12#\n" +
	"\rindustry_code\x18\x01 \x01(\tR\findustryCode\x12 \n" +
	"\vrequirement\x18\x02 \x01(\tR\vrequirement\x12'\n" +
	"\x0fcandidate_count\x18\x03 \x01(\x05R\x0ecandidateCount\x12'\n" +
	"\x0fgeneration_mode\x18\x04 \x01(\tR\x0egenerationMode\x12\x18\n" +
	"\asources\x18\x05 \x03(\tR\asources\x12!\n" +
	"\fagent_prompt\x18\x06 \x01(\tR\vagentPrompt\x12'\n" +
	"\x0finclude_scraped\x18\a \x01(\bR\x0eincludeScraped\x12+\n" +
	"\x11include_generated\x18\b \x01(\bR\x10includeGenerated\"\xc9\x01\n" +
	"\"GenerateQuestionCandidatesResponse\x12#\n" +
	"\rindustry_code\x18\x01 \x01(\tR\findustryCode\x12 \n" +
	"\vrequirement\x18\x02 \x01(\tR\vrequirement\x12@\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2 .makejob.ai.v1.QuestionCandidateR\n" +
	"candidates\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"\xc6\x03\n" +
	"\x11QuestionCandidate\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06answer\x18\x06 \x01(\tR\x06answer\x12 \n" +
	"\vexplanation\x18\a \x01(\tR\vexplanation\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1f\n" +
	"\vsource_type\x18\t \x01(\tR\n" +
	"sourceType\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bsolution\x18\v \x01(\tR\bsolution\x12!\n" +
	"\fjudge_config\x18\f \x01(\tR\vjudgeConfig\x12!\n" +
	"\fsource_label\x18\r \x01(\tR\vsourceLabel\x12!\n" +
	"\fsource_title\x18\x0e \x01(\tR\vsourceTitle\x12\x1d\n" +
	"\n" +
	"source_url\x18\x0f \x01(\tR\tsourceUrl\"\xfc\x03\n" +
	"\x1bQuestionPipelineStreamEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"raw_output\x18\x04 \x01(\tR\trawOutput\x12#\n" +
	"\rfailure_stage\x18\x05 \x01(\tR\ffailureStage\x12+\n" +
	"\x11candidate_excerpt\x18\x06 \x01(\tR\x10candidateExcerpt\x12)\n" +
	"\x10repair_attempted\x18\a \x01(\bR\x0frepairAttempted\x121\n" +
	"\x14supplement_attempted\x18\b \x01(\bR\x13supplementAttempted\x12\x1d\n" +
	"\n" +
	"slot_index\x18\t \x01(\x05R\tslotIndex\x12\x1f\n" +
	"\vretry_index\x18\n" +
	" \x01(\x05R\n" +
	"retryIndex\x124\n" +
	"\x04card\x18\v \x01(\v2 .makejob.ai.v1.QuestionCandidateR\x04card\x12M\n" +
	"\bresponse\x18\f \x01(\v21.makejob.ai.v1.GenerateQuestionCandidatesResponseR\bresponse2\xd8\a\n" +
	"\tAIService\x12]\n" +
	"\x0eInterviewAgent\x12$.makejob.ai.v1.InterviewAgentRequest\x1a%.makejob.ai.v1.InterviewAgentResponse\x12N\n" +
	"\tPlanAgent\x12\x1f.makejob.ai.v1.PlanAgentRequest\x1a .makejob.ai.v1.PlanAgentResponse\x12]\n" +
	"\x0eCompanionAgent\x12$.makejob.ai.v1.CompanionAgentRequest\x1a%.makejob.ai.v1.CompanionAgentResponse\x12W\n" +
	"\fQuizAnalyzer\x12\".makejob.ai.v1.QuizAnalyzerRequest\x1a#.makejob.ai.v1.QuizAnalyzerResponse\x12W\n" +
	"\fResumeParser\x12\".makejob.ai.v1.ResumeParserRequest\x1a#.makejob.ai.v1.ResumeParserResponse\x12_\n" +
	"\x0eLive2DDirector\x12%.makejob.ai.v1.Live2DDirectiveRequest\x1a&.makejob.ai.v1.Live2DDirectiveResponse\x12W\n" +
	"\fRenderPrompt\x12\".makejob.ai.v1.RenderPromptRequest\x1a#.makejob.ai.v1.RenderPromptResponse\x12H\n" +
	"\aDebugAI\x12\x1d.makejob.ai.v1.DebugAIRequest\x1a\x1e.makejob.ai.v1.DebugAIResponse\x12\x81\x01\n" +
	"\x1aGenerateQuestionCandidates\x120.makejob.ai.v1.GenerateQuestionCandidatesRequest\x1a1.makejob.ai.v1.GenerateQuestionCandidatesResponse\x12\x82\x01\n" +
	" GenerateQuestionCandidatesStream\x120.makejob.ai.v1.GenerateQuestionCandidatesRequest\x1a*.makejob.ai.v1.QuestionPipelineStreamEvent0\x01B Z\x1emakejob/api/makejob/ai/v1;aiv1b\x06proto3"

var (
	file_makejob_ai_v1_ai_proto_rawDescOnce sync.Once
	file_makejob_ai_v1_ai_proto_rawDescData []byte
)

func file_makejob_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_makejob_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_makejob_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_ai_v1_ai_proto_rawDesc), len(file_makejob_ai_v1_ai_proto_rawDesc)))
	})
	return file_makejob_ai_v1_ai_proto_rawDescData
}

var file_makejob_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_makejob_ai_v1_ai_proto_goTypes = []any{
	(*InterviewAgentRequest)(nil),              // 0: makejob.ai.v1.InterviewAgentRequest
	(*Message)(nil),                            // 1: makejob.ai.v1.Message
	(*InterviewAgentResponse)(nil),             // 2: makejob.ai.v1.InterviewAgentResponse
	(*PlanAgentRequest)(nil),                   // 3: makejob.ai.v1.PlanAgentRequest
	(*PlanAgentResponse)(nil),                  // 4: makejob.ai.v1.PlanAgentResponse
	(*PlanTask)(nil),                           // 5: makejob.ai.v1.PlanTask
	(*CompanionAgentRequest)(nil),              // 6: makejob.ai.v1.CompanionAgentRequest
	(*CompanionAgentResponse)(nil),             // 7: makejob.ai.v1.CompanionAgentResponse
	(*QuizAnalyzerRequest)(nil),                // 8: makejob.ai.v1.QuizAnalyzerRequest
	(*QuizAnalyzerResponse)(nil),               // 9: makejob.ai.v1.QuizAnalyzerResponse
	(*ResumeParserRequest)(nil),                // 10: makejob.ai.v1.ResumeParserRequest
	(*ResumeParserResponse)(nil),               // 11: makejob.ai.v1.ResumeParserResponse
	(*Live2DDirectiveRequest)(nil),             // 12: makejob.ai.v1.Live2DDirectiveRequest
	(*Live2DDirectiveResponse)(nil),            // 13: makejob.ai.v1.Live2DDirectiveResponse
	(*RenderPromptRequest)(nil),                // 14: makejob.ai.v1.RenderPromptRequest
	(*RenderPromptResponse)(nil),               // 15: makejob.ai.v1.RenderPromptResponse
	(*DebugAIRequest)(nil),                     // 16: makejob.ai.v1.DebugAIRequest
	(*DebugAIResponse)(nil),                    // 17: makejob.ai.v1.DebugAIResponse
	(*GenerateQuestionCandidatesRequest)(nil),  // 18: makejob.ai.v1.GenerateQuestionCandidatesRequest
	(*GenerateQuestionCandidatesResponse)(nil), // 19: makejob.ai.v1.GenerateQuestionCandidatesResponse
	(*QuestionCandidate)(nil),                  // 20: makejob.ai.v1.QuestionCandidate
	(*QuestionPipelineStreamEvent)(nil),        // 21: makejob.ai.v1.QuestionPipelineStreamEvent
	nil,                                        // 22: makejob.ai.v1.RenderPromptRequest.VariablesEntry
	nil,                                        // 23: makejob.ai.v1.RenderPromptResponse.ResolvedVariablesEntry
	nil,                                        // 24: makejob.ai.v1.DebugAIRequest.ParamsEntry
}
var file_makejob_ai_v1_ai_proto_depIdxs = []int32{
	1,  // 0: makejob.ai.v1.InterviewAgentRequest.history:type_name -> makejob.ai.v1.Message
	5,  // 1: makejob.ai.v1.PlanAgentResponse.tasks:type_name -> makejob.ai.v1.PlanTask
	22, // 2: makejob.ai.v1.RenderPromptRequest.variables:type_name -> makejob.ai.v1.RenderPromptRequest.VariablesEntry
	23, // 3: makejob.ai.v1.RenderPromptResponse.resolved_variables:type_name -> makejob.ai.v1.RenderPromptResponse.ResolvedVariablesEntry
	24, // 4: makejob.ai.v1.DebugAIRequest.params:type_name -> makejob.ai.v1.DebugAIRequest.ParamsEntry
	20, // 5: makejob.ai.v1.GenerateQuestionCandidatesResponse.candidates:type_name -> makejob.ai.v1.QuestionCandidate
	20, // 6: makejob.ai.v1.QuestionPipelineStreamEvent.card:type_name -> makejob.ai.v1.QuestionCandidate
	19, // 7: makejob.ai.v1.QuestionPipelineStreamEvent.response:type_name -> makejob.ai.v1.GenerateQuestionCandidatesResponse
	0,  // 8: makejob.ai.v1.AIService.InterviewAgent:input_type -> makejob.ai.v1.InterviewAgentRequest
	3,  // 9: makejob.ai.v1.AIService.PlanAgent:input_type -> makejob.ai.v1.PlanAgentRequest
	6,  // 10: makejob.ai.v1.AIService.CompanionAgent:input_type -> makejob.ai.v1.CompanionAgentRequest
	8,  // 11: makejob.ai.v1.AIService.QuizAnalyzer:input_type -> makejob.ai.v1.QuizAnalyzerRequest
	10, // 12: makejob.ai.v1.AIService.ResumeParser:input_type -> makejob.ai.v1.ResumeParserRequest
	12, // 13: makejob.ai.v1.AIService.Live2DDirector:input_type -> makejob.ai.v1.Live2DDirectiveRequest
	14, // 14: makejob.ai.v1.AIService.RenderPrompt:input_type -> makejob.ai.v1.RenderPromptRequest
	16, // 15: makejob.ai.v1.AIService.DebugAI:input_type -> makejob.ai.v1.DebugAIRequest
	18, // 16: makejob.ai.v1.AIService.GenerateQuestionCandidates:input_type -> makejob.ai.v1.GenerateQuestionCandidatesRequest
	18, // 17: makejob.ai.v1.AIService.GenerateQuestionCandidatesStream:input_type -> makejob.ai.v1.GenerateQuestionCandidatesRequest
	2,  // 18: makejob.ai.v1.AIService.InterviewAgent:output_type -> makejob.ai.v1.InterviewAgentResponse
	4,  // 19: makejob.ai.v1.AIService.PlanAgent:output_type -> makejob.ai.v1.PlanAgentResponse
	7,  // 20: makejob.ai.v1.AIService.CompanionAgent:output_type -> makejob.ai.v1.CompanionAgentResponse
	9,  // 21: makejob.ai.v1.AIService.QuizAnalyzer:output_type -> makejob.ai.v1.QuizAnalyzerResponse
	11, // 22: makejob.ai.v1.AIService.ResumeParser:output_type -> makejob.ai.v1.ResumeParserResponse
	13, // 23: makejob.ai.v1.AIService.Live2DDirector:output_type -> makejob.ai.v1.Live2DDirectiveResponse
	15, // 24: makejob.ai.v1.AIService.RenderPrompt:output_type -> makejob.ai.v1.RenderPromptResponse
	17, // 25: makejob.ai.v1.AIService.DebugAI:output_type -> makejob.ai.v1.DebugAIResponse
	19, // 26: makejob.ai.v1.AIService.GenerateQuestionCandidates:output_type -> makejob.ai.v1.GenerateQuestionCandidatesResponse
	21, // 27: makejob.ai.v1.AIService.GenerateQuestionCandidatesStream:output_type -> makejob.ai.v1.QuestionPipelineStreamEvent
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_makejob_ai_v1_ai_proto_init() }
func file_makejob_ai_v1_ai_proto_init() {
	if File_makejob_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_ai_v1_ai_proto_rawDesc), len(file_makejob_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_makejob_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_makejob_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_makejob_ai_v1_ai_proto = out.File
	file_makejob_ai_v1_ai_proto_goTypes = nil
	file_makejob_ai_v1_ai_proto_depIdxs = nil
}
