// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: makejob/ai/v1/ai.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_InterviewAgent_FullMethodName = "/makejob.ai.v1.AIService/InterviewAgent"
	AIService_PlanAgent_FullMethodName      = "/makejob.ai.v1.AIService/PlanAgent"
	AIService_CompanionAgent_FullMethodName = "/makejob.ai.v1.AIService/CompanionAgent"
	AIService_QuizAnalyzer_FullMethodName   = "/makejob.ai.v1.AIService/QuizAnalyzer"
	AIService_ResumeParser_FullMethodName   = "/makejob.ai.v1.AIService/ResumeParser"
	AIService_Live2DDirector_FullMethodName = "/makejob.ai.v1.AIService/Live2DDirector"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	InterviewAgent(ctx context.Context, in *InterviewAgentRequest, opts ...grpc.CallOption) (*InterviewAgentResponse, error)
	PlanAgent(ctx context.Context, in *PlanAgentRequest, opts ...grpc.CallOption) (*PlanAgentResponse, error)
	CompanionAgent(ctx context.Context, in *CompanionAgentRequest, opts ...grpc.CallOption) (*CompanionAgentResponse, error)
	QuizAnalyzer(ctx context.Context, in *QuizAnalyzerRequest, opts ...grpc.CallOption) (*QuizAnalyzerResponse, error)
	ResumeParser(ctx context.Context, in *ResumeParserRequest, opts ...grpc.CallOption) (*ResumeParserResponse, error)
	Live2DDirector(ctx context.Context, in *Live2DDirectiveRequest, opts ...grpc.CallOption) (*Live2DDirectiveResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) InterviewAgent(ctx context.Context, in *InterviewAgentRequest, opts ...grpc.CallOption) (*InterviewAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterviewAgentResponse)
	err := c.cc.Invoke(ctx, AIService_InterviewAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) PlanAgent(ctx context.Context, in *PlanAgentRequest, opts ...grpc.CallOption) (*PlanAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanAgentResponse)
	err := c.cc.Invoke(ctx, AIService_PlanAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) CompanionAgent(ctx context.Context, in *CompanionAgentRequest, opts ...grpc.CallOption) (*CompanionAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanionAgentResponse)
	err := c.cc.Invoke(ctx, AIService_CompanionAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) QuizAnalyzer(ctx context.Context, in *QuizAnalyzerRequest, opts ...grpc.CallOption) (*QuizAnalyzerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuizAnalyzerResponse)
	err := c.cc.Invoke(ctx, AIService_QuizAnalyzer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ResumeParser(ctx context.Context, in *ResumeParserRequest, opts ...grpc.CallOption) (*ResumeParserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeParserResponse)
	err := c.cc.Invoke(ctx, AIService_ResumeParser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) Live2DDirector(ctx context.Context, in *Live2DDirectiveRequest, opts ...grpc.CallOption) (*Live2DDirectiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Live2DDirectiveResponse)
	err := c.cc.Invoke(ctx, AIService_Live2DDirector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	InterviewAgent(context.Context, *InterviewAgentRequest) (*InterviewAgentResponse, error)
	PlanAgent(context.Context, *PlanAgentRequest) (*PlanAgentResponse, error)
	CompanionAgent(context.Context, *CompanionAgentRequest) (*CompanionAgentResponse, error)
	QuizAnalyzer(context.Context, *QuizAnalyzerRequest) (*QuizAnalyzerResponse, error)
	ResumeParser(context.Context, *ResumeParserRequest) (*ResumeParserResponse, error)
	Live2DDirector(context.Context, *Live2DDirectiveRequest) (*Live2DDirectiveResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) InterviewAgent(context.Context, *InterviewAgentRequest) (*InterviewAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InterviewAgent not implemented")
}
func (UnimplementedAIServiceServer) PlanAgent(context.Context, *PlanAgentRequest) (*PlanAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanAgent not implemented")
}
func (UnimplementedAIServiceServer) CompanionAgent(context.Context, *CompanionAgentRequest) (*CompanionAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompanionAgent not implemented")
}
func (UnimplementedAIServiceServer) QuizAnalyzer(context.Context, *QuizAnalyzerRequest) (*QuizAnalyzerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuizAnalyzer not implemented")
}
func (UnimplementedAIServiceServer) ResumeParser(context.Context, *ResumeParserRequest) (*ResumeParserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeParser not implemented")
}
func (UnimplementedAIServiceServer) Live2DDirector(context.Context, *Live2DDirectiveRequest) (*Live2DDirectiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Live2DDirector not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_InterviewAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterviewAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).InterviewAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_InterviewAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).InterviewAgent(ctx, req.(*InterviewAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_PlanAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).PlanAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_PlanAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).PlanAgent(ctx, req.(*PlanAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_CompanionAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanionAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CompanionAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CompanionAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CompanionAgent(ctx, req.(*CompanionAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_QuizAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuizAnalyzerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).QuizAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_QuizAnalyzer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).QuizAnalyzer(ctx, req.(*QuizAnalyzerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ResumeParser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ResumeParser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ResumeParser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ResumeParser(ctx, req.(*ResumeParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_Live2DDirector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Live2DDirectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).Live2DDirector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_Live2DDirector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).Live2DDirector(ctx, req.(*Live2DDirectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "makejob.ai.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InterviewAgent",
			Handler:    _AIService_InterviewAgent_Handler,
		},
		{
			MethodName: "PlanAgent",
			Handler:    _AIService_PlanAgent_Handler,
		},
		{
			MethodName: "CompanionAgent",
			Handler:    _AIService_CompanionAgent_Handler,
		},
		{
			MethodName: "QuizAnalyzer",
			Handler:    _AIService_QuizAnalyzer_Handler,
		},
		{
			MethodName: "ResumeParser",
			Handler:    _AIService_ResumeParser_Handler,
		},
		{
			MethodName: "Live2DDirector",
			Handler:    _AIService_Live2DDirector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "makejob/ai/v1/ai.proto",
}
