// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/coderunner/v1/coderunner.proto

package coderunnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Stdin         string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TestCases     []*TestCase            `protobuf:"bytes,4,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *ExecuteRequest) GetTestCases() []*TestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type TestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput string                 `protobuf:"bytes,2,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{1}
}

func (x *TestCase) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestCase) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

type ExecuteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Stdout          string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode        int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	TestResults     []*TestResult          `protobuf:"bytes,6,rep,name=test_results,json=testResults,proto3" json:"test_results,omitempty"`
	PassedCount     int32                  `protobuf:"varint,7,opt,name=passed_count,json=passedCount,proto3" json:"passed_count,omitempty"`
	TotalCount      int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// FIX: 添加spec要求的error字段
	Error         string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *ExecuteResponse) GetTestResults() []*TestResult {
	if x != nil {
		return x.TestResults
	}
	return nil
}

func (x *ExecuteResponse) GetPassedCount() int32 {
	if x != nil {
		return x.PassedCount
	}
	return 0
}

func (x *ExecuteResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TestResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Input           string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput  string                 `protobuf:"bytes,2,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	ActualOutput    string                 `protobuf:"bytes,3,opt,name=actual_output,json=actualOutput,proto3" json:"actual_output,omitempty"`
	Passed          bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{3}
}

func (x *TestResult) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TestResult) GetExpectedOutput() string {
	if x != nil {
		return x.ExpectedOutput
	}
	return ""
}

func (x *TestResult) GetActualOutput() string {
	if x != nil {
		return x.ActualOutput
	}
	return ""
}

func (x *TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *TestResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ListLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesRequest) Reset() {
	*x = ListLanguagesRequest{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesRequest) ProtoMessage() {}

func (x *ListLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{4}
}

type ListLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*LanguageInfo        `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesResponse) Reset() {
	*x = ListLanguagesResponse{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesResponse) ProtoMessage() {}

func (x *ListLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{5}
}

func (x *ListLanguagesResponse) GetLanguages() []*LanguageInfo {
	if x != nil {
		return x.Languages
	}
	return nil
}

type LanguageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageInfo) Reset() {
	*x = LanguageInfo{}
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageInfo) ProtoMessage() {}

func (x *LanguageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_coderunner_v1_coderunner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageInfo.ProtoReflect.Descriptor instead.
func (*LanguageInfo) Descriptor() ([]byte, []int) {
	return file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP(), []int{6}
}

func (x *LanguageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_makejob_coderunner_v1_coderunner_proto protoreflect.FileDescriptor

const file_makejob_coderunner_v1_coderunner_proto_rawDesc = "" +
	"\n" +
	"&makejob/coderunner/v1/coderunner.proto\x12\x15makejob.coderunner.v1\"\xb5\x01\n" +
	"\x0eExecuteRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12>\n" +
	"\n" +
	"test_cases\x18\x04 \x03(\v2\x1f.makejob.coderunner.v1.TestCaseR\ttestCases\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\"I\n" +
	"\bTestCase\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12'\n" +
	"\x0fexpected_output\x18\x02 \x01(\tR\x0eexpectedOutput\"\xc4\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\x12D\n" +
	"\ftest_results\x18\x06 \x03(\v2!.makejob.coderunner.v1.TestResultR\vtestResults\x12!\n" +
	"\fpassed_count\x18\a \x01(\x05R\vpassedCount\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\xb4\x01\n" +
	"\n" +
	"TestResult\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12'\n" +
	"\x0fexpected_output\x18\x02 \x01(\tR\x0eexpectedOutput\x12#\n" +
	"\ractual_output\x18\x03 \x01(\tR\factualOutput\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"\x16\n" +
	"\x14ListLanguagesRequest\"Z\n" +
	"\x15ListLanguagesResponse\x12A\n" +
	"\tlanguages\x18\x01 \x03(\v2#.makejob.coderunner.v1.LanguageInfoR\tlanguages\"<\n" +
	"\fLanguageInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xd9\x01\n" +
	"\x11CodeRunnerService\x12X\n" +
	"\aExecute\x12%.makejob.coderunner.v1.ExecuteRequest\x1a&.makejob.coderunner.v1.ExecuteResponse\x12j\n" +
	"\rListLanguages\x12+.makejob.coderunner.v1.ListLanguagesRequest\x1a,.makejob.coderunner.v1.ListLanguagesResponseB0Z.makejob/api/makejob/coderunner/v1;coderunnerv1b\x06proto3"

var (
	file_makejob_coderunner_v1_coderunner_proto_rawDescOnce sync.Once
	file_makejob_coderunner_v1_coderunner_proto_rawDescData []byte
)

func file_makejob_coderunner_v1_coderunner_proto_rawDescGZIP() []byte {
	file_makejob_coderunner_v1_coderunner_proto_rawDescOnce.Do(func() {
		file_makejob_coderunner_v1_coderunner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_coderunner_v1_coderunner_proto_rawDesc), len(file_makejob_coderunner_v1_coderunner_proto_rawDesc)))
	})
	return file_makejob_coderunner_v1_coderunner_proto_rawDescData
}

var file_makejob_coderunner_v1_coderunner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_makejob_coderunner_v1_coderunner_proto_goTypes = []any{
	(*ExecuteRequest)(nil),        // 0: makejob.coderunner.v1.ExecuteRequest
	(*TestCase)(nil),              // 1: makejob.coderunner.v1.TestCase
	(*ExecuteResponse)(nil),       // 2: makejob.coderunner.v1.ExecuteResponse
	(*TestResult)(nil),            // 3: makejob.coderunner.v1.TestResult
	(*ListLanguagesRequest)(nil),  // 4: makejob.coderunner.v1.ListLanguagesRequest
	(*ListLanguagesResponse)(nil), // 5: makejob.coderunner.v1.ListLanguagesResponse
	(*LanguageInfo)(nil),          // 6: makejob.coderunner.v1.LanguageInfo
}
var file_makejob_coderunner_v1_coderunner_proto_depIdxs = []int32{
	1, // 0: makejob.coderunner.v1.ExecuteRequest.test_cases:type_name -> makejob.coderunner.v1.TestCase
	3, // 1: makejob.coderunner.v1.ExecuteResponse.test_results:type_name -> makejob.coderunner.v1.TestResult
	6, // 2: makejob.coderunner.v1.ListLanguagesResponse.languages:type_name -> makejob.coderunner.v1.LanguageInfo
	0, // 3: makejob.coderunner.v1.CodeRunnerService.Execute:input_type -> makejob.coderunner.v1.ExecuteRequest
	4, // 4: makejob.coderunner.v1.CodeRunnerService.ListLanguages:input_type -> makejob.coderunner.v1.ListLanguagesRequest
	2, // 5: makejob.coderunner.v1.CodeRunnerService.Execute:output_type -> makejob.coderunner.v1.ExecuteResponse
	5, // 6: makejob.coderunner.v1.CodeRunnerService.ListLanguages:output_type -> makejob.coderunner.v1.ListLanguagesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_makejob_coderunner_v1_coderunner_proto_init() }
func file_makejob_coderunner_v1_coderunner_proto_init() {
	if File_makejob_coderunner_v1_coderunner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_coderunner_v1_coderunner_proto_rawDesc), len(file_makejob_coderunner_v1_coderunner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_coderunner_v1_coderunner_proto_goTypes,
		DependencyIndexes: file_makejob_coderunner_v1_coderunner_proto_depIdxs,
		MessageInfos:      file_makejob_coderunner_v1_coderunner_proto_msgTypes,
	}.Build()
	File_makejob_coderunner_v1_coderunner_proto = out.File
	file_makejob_coderunner_v1_coderunner_proto_goTypes = nil
	file_makejob_coderunner_v1_coderunner_proto_depIdxs = nil
}
