// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: makejob/rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IndexItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexQuestionsRequest) Reset() {
	*x = IndexQuestionsRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexQuestionsRequest) ProtoMessage() {}

func (x *IndexQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexQuestionsRequest.ProtoReflect.Descriptor instead.
func (*IndexQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *IndexQuestionsRequest) GetItems() []*IndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// FIX: 重命名为IndexItem以对齐spec
type IndexItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexItem) Reset() {
	*x = IndexItem{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexItem) ProtoMessage() {}

func (x *IndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexItem.ProtoReflect.Descriptor instead.
func (*IndexItem) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *IndexItem) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *IndexItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IndexItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexedCount  int32                  `protobuf:"varint,1,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexQuestionsResponse) Reset() {
	*x = IndexQuestionsResponse{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexQuestionsResponse) ProtoMessage() {}

func (x *IndexQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexQuestionsResponse.ProtoReflect.Descriptor instead.
func (*IndexQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *IndexQuestionsResponse) GetIndexedCount() int32 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *IndexQuestionsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type IndexDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DocumentIndexItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentsRequest) Reset() {
	*x = IndexDocumentsRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentsRequest) ProtoMessage() {}

func (x *IndexDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentsRequest.ProtoReflect.Descriptor instead.
func (*IndexDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *IndexDocumentsRequest) GetItems() []*DocumentIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DocumentIndexItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentIndexItem) Reset() {
	*x = DocumentIndexItem{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIndexItem) ProtoMessage() {}

func (x *DocumentIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIndexItem.ProtoReflect.Descriptor instead.
func (*DocumentIndexItem) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentIndexItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentIndexItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentIndexItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DocumentIndexItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IndexDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexedCount  int32                  `protobuf:"varint,1,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentsResponse) Reset() {
	*x = IndexDocumentsResponse{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentsResponse) ProtoMessage() {}

func (x *IndexDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentsResponse.ProtoReflect.Descriptor instead.
func (*IndexDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *IndexDocumentsResponse) GetIndexedCount() int32 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *IndexDocumentsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteIndexRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexResponse) Reset() {
	*x = DeleteIndexResponse{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexResponse) ProtoMessage() {}

func (x *DeleteIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexResponse.ProtoReflect.Descriptor instead.
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteIndexResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{11}
}

type RAGConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	EmbeddingDimension int32                  `protobuf:"varint,2,opt,name=embedding_dimension,json=embeddingDimension,proto3" json:"embedding_dimension,omitempty"`
	EmbeddingModel     string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RAGConfig) Reset() {
	*x = RAGConfig{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGConfig) ProtoMessage() {}

func (x *RAGConfig) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGConfig.ProtoReflect.Descriptor instead.
func (*RAGConfig) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{12}
}

func (x *RAGConfig) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *RAGConfig) GetEmbeddingDimension() int32 {
	if x != nil {
		return x.EmbeddingDimension
	}
	return 0
}

func (x *RAGConfig) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

type UpdateConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	EmbeddingDimension int32                  `protobuf:"varint,2,opt,name=embedding_dimension,json=embeddingDimension,proto3" json:"embedding_dimension,omitempty"`
	EmbeddingModel     string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *UpdateConfigRequest) GetEmbeddingDimension() int32 {
	if x != nil {
		return x.EmbeddingDimension
	}
	return 0
}

func (x *UpdateConfigRequest) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{14}
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{15}
}

func (x *TestConnectionResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDocumentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentStatsRequest) Reset() {
	*x = GetDocumentStatsRequest{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentStatsRequest) ProtoMessage() {}

func (x *GetDocumentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentStatsRequest) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{16}
}

type DocumentStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalDocuments int64                  `protobuf:"varint,1,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	TotalQuestions int64                  `protobuf:"varint,2,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	LastIndexedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_indexed_at,json=lastIndexedAt,proto3" json:"last_indexed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentStats) Reset() {
	*x = DocumentStats{}
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStats) ProtoMessage() {}

func (x *DocumentStats) ProtoReflect() protoreflect.Message {
	mi := &file_makejob_rag_v1_rag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStats.ProtoReflect.Descriptor instead.
func (*DocumentStats) Descriptor() ([]byte, []int) {
	return file_makejob_rag_v1_rag_proto_rawDescGZIP(), []int{17}
}

func (x *DocumentStats) GetTotalDocuments() int64 {
	if x != nil {
		return x.TotalDocuments
	}
	return 0
}

func (x *DocumentStats) GetTotalQuestions() int64 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *DocumentStats) GetLastIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastIndexedAt
	}
	return nil
}

var File_makejob_rag_v1_rag_proto protoreflect.FileDescriptor

const file_makejob_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x18makejob/rag/v1/rag.proto\x12\x0emakejob.rag.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12F\n" +
	"\afilters\x18\x03 \x03(\v2,.makejob.rag.v1.RetrieveRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x10RetrieveResponse\x126\n" +
	"\tdocuments\x18\x01 \x03(\v2\x18.makejob.rag.v1.DocumentR\tdocuments\"\xcb\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.makejob.rag.v1.Document.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x15IndexQuestionsRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.makejob.rag.v1.IndexItemR\x05items\"\xc8\x01\n" +
	"\tIndexItem\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.makejob.rag.v1.IndexItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x16IndexQuestionsResponse\x12#\n" +
	"\rindexed_count\x18\x01 \x01(\x05R\findexedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\"P\n" +
	"\x15IndexDocumentsRequest\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.makejob.rag.v1.DocumentIndexItemR\x05items\"\xdf\x01\n" +
	"\x11DocumentIndexItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.makejob.rag.v1.DocumentIndexItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x16IndexDocumentsResponse\x12#\n" +
	"\rindexed_count\x18\x01 \x01(\x05R\findexedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\"&\n" +
	"\x12DeleteIndexRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\":\n" +
	"\x13DeleteIndexResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"\x12\n" +
	"\x10GetConfigRequest\"\x8e\x01\n" +
	"\tRAGConfig\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12/\n" +
	"\x13embedding_dimension\x18\x02 \x01(\x05R\x12embeddingDimension\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\"\x98\x01\n" +
	"\x13UpdateConfigRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12/\n" +
	"\x13embedding_dimension\x18\x02 \x01(\x05R\x12embeddingDimension\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\"\x17\n" +
	"\x15TestConnectionRequest\"P\n" +
	"\x16TestConnectionResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x19\n" +
	"\x17GetDocumentStatsRequest\"\xa5\x01\n" +
	"\rDocumentStats\x12'\n" +
	"\x0ftotal_documents\x18\x01 \x01(\x03R\x0etotalDocuments\x12'\n" +
	"\x0ftotal_questions\x18\x02 \x01(\x03R\x0etotalQuestions\x12B\n" +
	"\x0flast_indexed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastIndexedAt2\xcc\x05\n" +
	"\n" +
	"RAGService\x12M\n" +
	"\bRetrieve\x12\x1f.makejob.rag.v1.RetrieveRequest\x1a .makejob.rag.v1.RetrieveResponse\x12_\n" +
	"\x0eIndexQuestions\x12%.makejob.rag.v1.IndexQuestionsRequest\x1a&.makejob.rag.v1.IndexQuestionsResponse\x12_\n" +
	"\x0eIndexDocuments\x12%.makejob.rag.v1.IndexDocumentsRequest\x1a&.makejob.rag.v1.IndexDocumentsResponse\x12V\n" +
	"\vDeleteIndex\x12\".makejob.rag.v1.DeleteIndexRequest\x1a#.makejob.rag.v1.DeleteIndexResponse\x12H\n" +
	"\tGetConfig\x12 .makejob.rag.v1.GetConfigRequest\x1a\x19.makejob.rag.v1.RAGConfig\x12N\n" +
	"\fUpdateConfig\x12#.makejob.rag.v1.UpdateConfigRequest\x1a\x19.makejob.rag.v1.RAGConfig\x12_\n" +
	"\x0eTestConnection\x12%.makejob.rag.v1.TestConnectionRequest\x1a&.makejob.rag.v1.TestConnectionResponse\x12Z\n" +
	"\x10GetDocumentStats\x12'.makejob.rag.v1.GetDocumentStatsRequest\x1a\x1d.makejob.rag.v1.DocumentStatsB\"Z makejob/api/makejob/rag/v1;ragv1b\x06proto3"

var (
	file_makejob_rag_v1_rag_proto_rawDescOnce sync.Once
	file_makejob_rag_v1_rag_proto_rawDescData []byte
)

func file_makejob_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_makejob_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_makejob_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_makejob_rag_v1_rag_proto_rawDesc), len(file_makejob_rag_v1_rag_proto_rawDesc)))
	})
	return file_makejob_rag_v1_rag_proto_rawDescData
}

var file_makejob_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_makejob_rag_v1_rag_proto_goTypes = []any{
	(*RetrieveRequest)(nil),         // 0: makejob.rag.v1.RetrieveRequest
	(*RetrieveResponse)(nil),        // 1: makejob.rag.v1.RetrieveResponse
	(*Document)(nil),                // 2: makejob.rag.v1.Document
	(*IndexQuestionsRequest)(nil),   // 3: makejob.rag.v1.IndexQuestionsRequest
	(*IndexItem)(nil),               // 4: makejob.rag.v1.IndexItem
	(*IndexQuestionsResponse)(nil),  // 5: makejob.rag.v1.IndexQuestionsResponse
	(*IndexDocumentsRequest)(nil),   // 6: makejob.rag.v1.IndexDocumentsRequest
	(*DocumentIndexItem)(nil),       // 7: makejob.rag.v1.DocumentIndexItem
	(*IndexDocumentsResponse)(nil),  // 8: makejob.rag.v1.IndexDocumentsResponse
	(*DeleteIndexRequest)(nil),      // 9: makejob.rag.v1.DeleteIndexRequest
	(*DeleteIndexResponse)(nil),     // 10: makejob.rag.v1.DeleteIndexResponse
	(*GetConfigRequest)(nil),        // 11: makejob.rag.v1.GetConfigRequest
	(*RAGConfig)(nil),               // 12: makejob.rag.v1.RAGConfig
	(*UpdateConfigRequest)(nil),     // 13: makejob.rag.v1.UpdateConfigRequest
	(*TestConnectionRequest)(nil),   // 14: makejob.rag.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil),  // 15: makejob.rag.v1.TestConnectionResponse
	(*GetDocumentStatsRequest)(nil), // 16: makejob.rag.v1.GetDocumentStatsRequest
	(*DocumentStats)(nil),           // 17: makejob.rag.v1.DocumentStats
	nil,                             // 18: makejob.rag.v1.RetrieveRequest.FiltersEntry
	nil,                             // 19: makejob.rag.v1.Document.MetadataEntry
	nil,                             // 20: makejob.rag.v1.IndexItem.MetadataEntry
	nil,                             // 21: makejob.rag.v1.DocumentIndexItem.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 22: google.protobuf.Timestamp
}
var file_makejob_rag_v1_rag_proto_depIdxs = []int32{
	18, // 0: makejob.rag.v1.RetrieveRequest.filters:type_name -> makejob.rag.v1.RetrieveRequest.FiltersEntry
	2,  // 1: makejob.rag.v1.RetrieveResponse.documents:type_name -> makejob.rag.v1.Document
	19, // 2: makejob.rag.v1.Document.metadata:type_name -> makejob.rag.v1.Document.MetadataEntry
	4,  // 3: makejob.rag.v1.IndexQuestionsRequest.items:type_name -> makejob.rag.v1.IndexItem
	20, // 4: makejob.rag.v1.IndexItem.metadata:type_name -> makejob.rag.v1.IndexItem.MetadataEntry
	7,  // 5: makejob.rag.v1.IndexDocumentsRequest.items:type_name -> makejob.rag.v1.DocumentIndexItem
	21, // 6: makejob.rag.v1.DocumentIndexItem.metadata:type_name -> makejob.rag.v1.DocumentIndexItem.MetadataEntry
	22, // 7: makejob.rag.v1.DocumentStats.last_indexed_at:type_name -> google.protobuf.Timestamp
	0,  // 8: makejob.rag.v1.RAGService.Retrieve:input_type -> makejob.rag.v1.RetrieveRequest
	3,  // 9: makejob.rag.v1.RAGService.IndexQuestions:input_type -> makejob.rag.v1.IndexQuestionsRequest
	6,  // 10: makejob.rag.v1.RAGService.IndexDocuments:input_type -> makejob.rag.v1.IndexDocumentsRequest
	9,  // 11: makejob.rag.v1.RAGService.DeleteIndex:input_type -> makejob.rag.v1.DeleteIndexRequest
	11, // 12: makejob.rag.v1.RAGService.GetConfig:input_type -> makejob.rag.v1.GetConfigRequest
	13, // 13: makejob.rag.v1.RAGService.UpdateConfig:input_type -> makejob.rag.v1.UpdateConfigRequest
	14, // 14: makejob.rag.v1.RAGService.TestConnection:input_type -> makejob.rag.v1.TestConnectionRequest
	16, // 15: makejob.rag.v1.RAGService.GetDocumentStats:input_type -> makejob.rag.v1.GetDocumentStatsRequest
	1,  // 16: makejob.rag.v1.RAGService.Retrieve:output_type -> makejob.rag.v1.RetrieveResponse
	5,  // 17: makejob.rag.v1.RAGService.IndexQuestions:output_type -> makejob.rag.v1.IndexQuestionsResponse
	8,  // 18: makejob.rag.v1.RAGService.IndexDocuments:output_type -> makejob.rag.v1.IndexDocumentsResponse
	10, // 19: makejob.rag.v1.RAGService.DeleteIndex:output_type -> makejob.rag.v1.DeleteIndexResponse
	12, // 20: makejob.rag.v1.RAGService.GetConfig:output_type -> makejob.rag.v1.RAGConfig
	12, // 21: makejob.rag.v1.RAGService.UpdateConfig:output_type -> makejob.rag.v1.RAGConfig
	15, // 22: makejob.rag.v1.RAGService.TestConnection:output_type -> makejob.rag.v1.TestConnectionResponse
	17, // 23: makejob.rag.v1.RAGService.GetDocumentStats:output_type -> makejob.rag.v1.DocumentStats
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_makejob_rag_v1_rag_proto_init() }
func file_makejob_rag_v1_rag_proto_init() {
	if File_makejob_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_makejob_rag_v1_rag_proto_rawDesc), len(file_makejob_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_makejob_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_makejob_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_makejob_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_makejob_rag_v1_rag_proto = out.File
	file_makejob_rag_v1_rag_proto_goTypes = nil
	file_makejob_rag_v1_rag_proto_depIdxs = nil
}
